### ISSUE TITLE
重启服务器后无法登录

### ISSUE THREAD

**Issue by kettly1260** [blueset/efb-wechat-slave#101]
### 版本信息

Running on profile "default".

Master channel:
    Telegram Master (blueset.telegram) 2.0.3 # Default instance

Slave channel:
    WeChat Slave (blueset.wechat) 2.0.1 # Default instance

Middlewares:
    No middleware is enabled.

### 问题描述

重启服务器后重新登录，最开始还出现过确认登录的提示，确认登录后就再也无法登录，并出现如下提示。

### 重现步骤

重启服务器后重新登录，最开始还出现过确认登录的提示，确认登录后就再也无法登录，并出现如下提示。

### Verbose 日志
<details>
<summary>Verbose 日志</summary>

```
2020-04-17 17:59:29,634 [Level 99]: ehforwarderbot.__main__ (__main__.init; __main__.py:85)
     Initializing slave blueset.wechat... 
Traceback (most recent call last):
  File "/usr/local/bin/ehforwarderbot", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/ehforwarderbot/__main__.py", line 277, in main
    init(conf)
  File "/usr/local/lib/python3.6/site-packages/ehforwarderbot/__main__.py", line 91, in init
    coordinator.add_channel(cls(instance_id=instance_id))
  File "/usr/local/lib/python3.6/site-packages/efb_wechat_slave/__init__.py", line 157, in __init__
    self.authenticate('console_qr_code', first_start=True)
  File "/usr/local/lib/python3.6/site-packages/efb_wechat_slave/__init__.py", line 670, in authenticate
    self.flag('puid_logs')
  File "/usr/local/lib/python3.6/site-packages/efb_wechat_slave/vendor/wxpy/api/bot.py", line 181, in enable_puid
    self.puid_map = PuidMap(path, puid_logs)
  File "/usr/local/lib/python3.6/site-packages/efb_wechat_slave/vendor/wxpy/utils/puid_map.py", line 114, in __init__
    self.load()
  File "/usr/local/lib/python3.6/site-packages/efb_wechat_slave/vendor/wxpy/utils/puid_map.py", line 263, in load
    self.user_names, self.wxids, self.remark_names, self.captions = pickle.load(fp)
EOFError: Ran out of input

```
 
</details>

**Comment by blueset** [comment]
你的 `wxpy_puid.pkl` 文件被损坏。请尝试删除此文件然后重试。

注意：此文件失效后**所有会话将会被视为全新会话**。

建议更新到最新的 EWS 版本以规避将来可能发生的此问题。
