### ISSUE TITLE
Web WeChat logged your account out before master channel is ready.

### ISSUE THREAD

**Issue by shzxm** [blueset/efb-wechat-slave#106]
EH Forwarder Bot
版本: 2.0.0
Python 版本:
3.6.8 (default, Apr  2 2020, 13:34:55) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
正在使用配置文件「default」。

主端:
    Telegram Master (blueset.telegram) 2.1.0 # 默认实例

从端:
    WeChat Slave (blueset.wechat) 2.0.2 # 默认实例

中间件:
    尚未启用任何中间件。

### 问题描述
异地登录出现 无法登录问题

### 重现步骤
本地网络一直不稳定,更换vps到hk以后

!!!第一次登录可以正常使用!!!
但是掉线重连 或 登出重新登录

不再像以前一样提示 异地登陆
会出现下列错误

### Verbose 日志

2020-07-26 20:40:03,768 [Level 99]: plugins.blueset.wechat.WeChatChannel (__init__.console_qr_code; __init__.py:192)
    请在手机上确认。
2020-07-26 20:40:06,154 [Level 99]: plugins.blueset.wechat.WeChatChannel (__init__.console_qr_code; __init__.py:195)
    登录成功。
2020-07-26 20:40:07,468 [Level 99]: ehforwarderbot.__main__ (__main__.init; __main__.py:96)
     从端 WeChat Slave (blueset.wechat) # 默认配置档案 初始化成功。 
2020-07-26 20:40:07,472 [Level 99]: ehforwarderbot.__main__ (__main__.init; __main__.py:99)
     正在初始化主端 blueset.telegram… 
Exception in thread itchat polling thread (maintain_loop):
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/site-packages/efb_wechat_slave/vendor/itchat/components/login.py", line 295, in maintain_loop
    exitCallback()
  File "/usr/local/lib/python3.6/site-packages/efb_wechat_slave/__init__.py", line 262, in exit_callback
    self._("Web WeChat logged your account out before master channel is ready."))
Exception: 在主端完成准备之前，网页版微信已经将你登出。

2020-07-26 20:40:08,483 [Level 99]: ehforwarderbot.__main__ (__main__.init; __main__.py:109)
     主端 Telegram Master (blueset.telegram) # 默认配置档案 初始化成功。 
2020-07-26 20:40:08,484 [Level 99]: ehforwarderbot.__main__ (__main__.init; __main__.py:111)
     所有信道均已成功初始化。 
2020-07-26 20:40:08,484 [Level 99]: ehforwarderbot.__main__ (__main__.init; __main__.py:125)
     所有中间件都已初始化。

**Comment by shzxm** [comment]
![Snipaste_2020-07-26_21-01-31](https://user-images.githubusercontent.com/9905297/88479642-32e8bb80-cf83-11ea-92ec-4a2c60a9e0f8.png)

错误原因已经找到
貌似无法解决.

**Comment by shzxm** [comment]
已知解决办法
手机上  全局代理 当前要登录 vps 所在地的 代理
正常使用10分钟wechat
可解除 异常状态
