### ISSUE TITLE
Config files

### ISSUE THREAD

**Issue by shawnyip** [blueset/efb-wechat-slave#15]
Can you provide the config files. I just using telegram as master and wechat as slave. I cannot find any example on the web but I cannot config the bot.

Here is my config 

```
master_channel: blueset.telegram
slave_channel:
- blueset.wechat
```

And ehforwarderbot return 
```
Traceback (most recent call last):
  File "/usr/local/bin/ehforwarderbot", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/ehforwarderbot/__main__.py", line 169, in main
    init()
  File "/usr/local/lib/python3.6/site-packages/ehforwarderbot/__main__.py", line 74, in init
    conf = config.load_config()
  File "/usr/local/lib/python3.6/site-packages/ehforwarderbot/config.py", line 43, in load_config
    raise ValueError("Slave Channel paths must be a list.")
ValueError: Slave Channel paths must be a list.

```

**Comment by blueset** [comment]
The array key for slave channel IDs should be `slave_channels`. There was a typo in the docs, and the example below is correct. 

Thanks for your feedback.
