### ISSUE TITLE
查询任意微信会话失效

### ISSUE THREAD

**Issue by cxumol** [blueset/efb-wechat-slave#18]
### 版本信息

```
EH Forwarder Bot
Version: 2.0.0b10
Python version:
3.6.2 |Continuum Analytics, Inc.| (default, Jul 20 2017, 13:51:32) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]

Master channel:
    Telegram Master (blueset.telegram) 2.0.0b11 # Default profile

Slave channel:
    WeChat Slave (blueset.wechat) 2.0.0a12
```
### 问题描述

ETM 向 EWS  输入 `/link ${chat}` 或  `/link ${chat}` 后,
ETM 返回 "处理中…" 或 "Processing..." , 且无后续变化  
同时, 后台 log 报 "TypeError" 错误 (详见后文)

### 重现步骤

> 不好确认复现条件. 
刚换到 v2 的头两天, 能正常搜到会话.
期间没有更新过后台程序/依赖, 只掉线重新扫过两次码. 
前天突然出现这个问题

### Verbose 日志
<details>
<summary>Traceback </summary>

```log
2018-04-08 17:20:24,852 [ERROR]: telegram.ext.dispatcher (dispatcher.process_update; dispatcher.py:301) 
    An uncaught error was raised while processing the update
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/lib/python3.6/site-packages/telegram/ext/dispatcher.py", line 279, in process_update
    handler.handle_update(update, self)
  File "/home/ubuntu/miniconda3/lib/python3.6/site-packages/telegram/ext/commandhandler.py", line 170, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "/home/ubuntu/miniconda3/lib/python3.6/site-packages/efb_telegram_master/chat_binding.py", line 256, in link_chat_show_list
    return self.link_chat_gen_list(message.from_user.id, pattern=" ".join(args))
  File "/home/ubuntu/miniconda3/lib/python3.6/site-packages/efb_telegram_master/chat_binding.py", line 408, in link_chat_gen_list
    source_chats=chats)
  File "/home/ubuntu/miniconda3/lib/python3.6/site-packages/efb_telegram_master/chat_binding.py", line 315, in slave_chats_pagination
    slave_chats = slave.get_chats()
  File "/home/ubuntu/miniconda3/lib/python3.6/site-packages/efb_wechat_slave/__init__.py", line 544, in get_chats
    return self.chats.get_chats()
  File "/home/ubuntu/miniconda3/lib/python3.6/site-packages/efb_wechat_slave/chats.py", line 108, in get_chats
    l.append(self.wxpy_chat_to_efb_chat(i))
  File "/home/ubuntu/miniconda3/lib/python3.6/site-packages/efb_wechat_slave/chats.py", line 88, in wxpy_chat_to_efb_chat
    efb_chat.members.append(self.wxpy_chat_to_efb_chat(i, False))
  File "/home/ubuntu/miniconda3/lib/python3.6/site-packages/efb_wechat_slave/chats.py", line 68, in wxpy_chat_to_efb_chat
    self.logger.debug("WXPY chat with ID: %s, name: %s, alias: %s;", chat.puid, chat.nick_name, chat.alias)
  File "/home/ubuntu/miniconda3/lib/python3.6/site-packages/efb_wechat_slave/wxpy/api/chats/chat.py", line 112, in puid
    return self.bot.puid_map.get_puid(self)
  File "/home/ubuntu/miniconda3/lib/python3.6/site-packages/efb_wechat_slave/wxpy/utils/puid_map.py", line 152, in get_puid
    new_caption = merge_captions(self.captions.get_key(puid), chat_caption)
  File "/home/ubuntu/miniconda3/lib/python3.6/site-packages/efb_wechat_slave/wxpy/utils/puid_map.py", line 247, in merge_captions
    return tuple(new[i] or old[i] for i in range(4))
  File "/home/ubuntu/miniconda3/lib/python3.6/site-packages/efb_wechat_slave/wxpy/utils/puid_map.py", line 247, in <genexpr>
    return tuple(new[i] or old[i] for i in range(4))
TypeError: 'NoneType' object is not subscriptable
```
 
</details>

**Comment by wolfsilver** [comment]
同样偶然遇到这个问题，删掉`blueset.wechat`下的pkl文件就好了

**Comment by blueset** [comment]
Duplicate of #23.

已尝试修复。
