### ISSUE TITLE
经常丢消息

### ISSUE THREAD

**Issue by AkazaDorian** [blueset/efb-wechat-slave#20]
某条消息的 log 如下

```
Apr 20 11:57:13 MACHINE ehforwarderbot[6606]: 2018-04-20 11:57:13,152 [ERROR]: efb_telegram_master.slave_message (slave_message.send_message; slave_message.py:176)
Apr 20 11:57:13 MACHINE ehforwarderbot[6606]:     [5573409930885243845] Error occurred while processing message from slave channel.
Apr 20 11:57:13 MACHINE ehforwarderbot[6606]: Message: <EFBMsg, <EFBChat: Ziv（999） (17 ziv bug, 83afd701) @ WeChat Slave>@<EFBChat: 群名 (af2f0c8d) @ WeChat Slave> [Text]: 而且有厨房; Attributes: None; Delivering to: <efb_telegram_master.TelegramChannel object at 0x7efff5d00d68>; Edited: False; System message: False; Substitutions: None; Target messages: None; UID: 5573409930885243845;File: None (None @ None), None; Vendor: {}>
而且有厨房; Att
Apr 20 11:57:13 MACHINE ehforwarderbot[6606]: TimedOut()
Apr 20 11:57:13 MACHINE ehforwarderbot[6606]: Traceback (most recent call last):
Apr 20 11:57:13 MACHINE ehforwarderbot[6606]:   File "/usr/local/lib/python3.6/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 402, in _make_request
Apr 20 11:57:13 MACHINE ehforwarderbot[6606]:     six.raise_from(e, None)
Apr 20 11:57:13 MACHINE ehforwarderbot[6606]:   File "<string>", line 2, in raise_from
Apr 20 11:57:13 MACHINE ehforwarderbot[6606]:   File "/usr/local/lib/python3.6/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 398, in _make_request
Apr 20 11:57:13 MACHINE ehforwarderbot[6606]:     httplib_response = conn.getresponse()
Apr 20 11:57:13 MACHINE ehforwarderbot[6606]:   File "/usr/local/lib/python3.6/http/client.py", line 1331, in getresponse
Apr 20 11:57:13 MACHINE ehforwarderbot[6606]:     response.begin()
Apr 20 11:57:13 MACHINE ehforwarderbot[6606]:   File "/usr/local/lib/python3.6/http/client.py", line 297, in begin
Apr 20 11:57:13 MACHINE ehforwarderbot[6606]:     version, status, reason = self._read_status()
Apr 20 11:57:13 MACHINE ehforwarderbot[6606]:   File "/usr/local/lib/python3.6/http/client.py", line 258, in _read_status
Apr 20 11:57:13 MACHINE ehforwarderbot[6606]:     line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
Apr 20 11:57:13 MACHINE ehforwarderbot[6606]:   File "/usr/local/lib/python3.6/socket.py", line 586, in readinto
Apr 20 11:57:13 MACHINE ehforwarderbot[6606]:     return self._sock.recv_into(b)
Apr 20 11:57:13 MACHINE ehforwarderbot[6606]:   File "/usr/local/lib/python3.6/ssl.py", line 1009, in recv_into
Apr 20 11:57:13 MACHINE ehforwarderbot[6606]:     return self.read(nbytes, buffer)
Apr 20 11:57:13 MACHINE ehforwarderbot[6606]:   File "/usr/local/lib/python3.6/ssl.py", line 871, in read
Apr 20 11:57:13 MACHINE ehforwarderbot[6606]:     return self._sslobj.read(len, buffer)
Apr 20 11:57:13 MACHINE ehforwarderbot[6606]:   File "/usr/local/lib/python3.6/ssl.py", line 631, in read
Apr 20 11:57:13 MACHINE ehforwarderbot[6606]:     v = self._sslobj.read(len, buffer)
Apr 20 11:57:13 MACHINE ehforwarderbot[6606]: socket.timeout: The read operation timed out
Apr 20 11:57:13 MACHINE ehforwarderbot[6606]: During handling of the above exception, another exception occurred:
Apr 20 11:57:13 MACHINE ehforwarderbot[6606]: Traceback (most recent call last):
Apr 20 11:57:13 MACHINE ehforwarderbot[6606]:   File "/usr/local/lib/python3.6/site-packages/telegram/utils/request.py", line 190, in _request_wrapper
Apr 20 11:57:13 MACHINE ehforwarderbot[6606]:     resp = self._con_pool.request(*args, **kwargs)
Apr 20 11:57:13 MACHINE ehforwarderbot[6606]:   File "/usr/local/lib/python3.6/site-packages/telegram/vendor/ptb_urllib3/urllib3/request.py", line 70, in request
Apr 20 11:57:13 MACHINE ehforwarderbot[6606]:     **urlopen_kw)
Apr 20 11:57:13 MACHINE ehforwarderbot[6606]:   File "/usr/local/lib/python3.6/site-packages/telegram/vendor/ptb_urllib3/urllib3/request.py", line 148, in request_encode_body
Apr 20 11:57:13 MACHINE ehforwarderbot[6606]:     return self.urlopen(method, url, **extra_kw)
Apr 20 11:57:13 MACHINE ehforwarderbot[6606]:   File "/usr/local/lib/python3.6/site-packages/telegram/vendor/ptb_urllib3/urllib3/poolmanager.py", line 244, in urlopen
Apr 20 11:57:13 MACHINE ehforwarderbot[6606]:     response = conn.urlopen(method, u.request_uri, **kw)
Apr 20 11:57:13 MACHINE ehforwarderbot[6606]:   File "/usr/local/lib/python3.6/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 666, in urlopen
Apr 20 11:57:13 MACHINE ehforwarderbot[6606]:     _stacktrace=sys.exc_info()[2])
Apr 20 11:57:13 MACHINE ehforwarderbot[6606]:   File "/usr/local/lib/python3.6/site-packages/telegram/vendor/ptb_urllib3/urllib3/util/retry.py", line 347, in increment
Apr 20 11:57:13 MACHINE ehforwarderbot[6606]:     raise six.reraise(type(error), error, _stacktrace)
Apr 20 11:57:13 MACHINE ehforwarderbot[6606]:   File "/usr/local/lib/python3.6/site-packages/telegram/vendor/ptb_urllib3/urllib3/packages/six.py", line 686, in reraise
Apr 20 11:57:13 MACHINE ehforwarderbot[6606]:     raise value
Apr 20 11:57:13 MACHINE ehforwarderbot[6606]:   File "/usr/local/lib/python3.6/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 617, in urlopen
Apr 20 11:57:13 MACHINE ehforwarderbot[6606]:     chunked=chunked)
Apr 20 11:57:13 MACHINE ehforwarderbot[6606]:   File "/usr/local/lib/python3.6/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 405, in _make_requestApr 20 11:57:13 MACHINE ehforwarderbot[6606]:     exc_cls=ReadTimeoutError)
Apr 20 11:57:13 MACHINE ehforwarderbot[6606]:   File "/usr/local/lib/python3.6/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 321, in _raise_timeout
Apr 20 11:57:13 MACHINE ehforwarderbot[6606]:     raise exc_cls(*args)
Apr 20 11:57:13 MACHINE ehforwarderbot[6606]: telegram.vendor.ptb_urllib3.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read t
Apr 20 11:57:13 MACHINE ehforwarderbot[6606]: During handling of the above exception, another exception occurred:
Apr 20 11:57:13 MACHINE ehforwarderbot[6606]: Traceback (most recent call last):
Apr 20 11:57:13 MACHINE ehforwarderbot[6606]:   File "/usr/local/lib/python3.6/site-packages/efb_telegram_master/slave_message.py", line 132, in send_message
Apr 20 11:57:13 MACHINE ehforwarderbot[6606]:     tg_msg = self.slave_message_text(msg, tg_dest, msg_template, old_msg_id, target_msg_id, reply_markup)
Apr 20 11:57:13 MACHINE ehforwarderbot[6606]:   File "/usr/local/lib/python3.6/site-packages/efb_telegram_master/slave_message.py", line 197, in slave_message_text
Apr 20 11:57:13 MACHINE ehforwarderbot[6606]:     self.bot.send_chat_action(tg_dest, telegram.ChatAction.TYPING)
Apr 20 11:57:13 MACHINE ehforwarderbot[6606]:   File "/usr/local/lib/python3.6/site-packages/efb_telegram_master/bot_manager.py", line 333, in send_chat_action
Apr 20 11:57:13 MACHINE ehforwarderbot[6606]:     return self.updater.bot.send_chat_action(*args, **kwargs)
Apr 20 11:57:13 MACHINE ehforwarderbot[6606]:   File "/usr/local/lib/python3.6/site-packages/telegram/bot.py", line 60, in decorator
Apr 20 11:57:13 MACHINE ehforwarderbot[6606]:     result = func(self, *args, **kwargs)
Apr 20 11:57:13 MACHINE ehforwarderbot[6606]:   File "/usr/local/lib/python3.6/site-packages/telegram/bot.py", line 1224, in send_chat_action
Apr 20 11:57:13 MACHINE ehforwarderbot[6606]:     result = self._request.post(url, data, timeout=timeout)
Apr 20 11:57:13 MACHINE ehforwarderbot[6606]:   File "/usr/local/lib/python3.6/site-packages/telegram/utils/request.py", line 273, in post
Apr 20 11:57:13 MACHINE ehforwarderbot[6606]:     **urlopen_kwargs)
Apr 20 11:57:13 MACHINE ehforwarderbot[6606]:   File "/usr/local/lib/python3.6/site-packages/telegram/utils/request.py", line 192, in _request_wrapper
Apr 20 11:57:13 MACHINE ehforwarderbot[6606]:     raise TimedOut()
Apr 20 11:57:13 MACHINE ehforwarderbot[6606]: telegram.error.TimedOut: Timed out


```

**Comment by blueset** [comment]
请确保服务器与 Telegram API 的通讯状态稳定。
