### ISSUE TITLE
[BUG REPORT] ValueError: Deliver_to is not valid.

### ISSUE THREAD

**Issue by blueset** [blueset/efb-wechat-slave#21]
_From @oyrx on April 22, 2018 4:37_

## BUG description:

- **When:**

It occurs when attempting to login WeChat.

- **Details:**

Console logs `ValueError: Deliver_to is not valid.` after successfully logging in with QR code, while no Web-WeChat using status in WeChat app and the bot doesn't work.

## Log:
```
.......................... upper logs has been ignored .....................................

Please scan the QR code to log in.
2018-04-22 12:18:18,281 [INFO]: itchat (login.login; login.py:50) 
    Please scan the QR code to log in.
2018-04-22 12:18:26,909 [Level 99]: plugins.blueset.wechat.WeChatChannel (__init__.console_qr_code; __init__.py:203) 
    Confirm on your phone.
Please press confirm on your phone.
2018-04-22 12:18:26,910 [INFO]: itchat (login.login; login.py:60) 
    Please press confirm on your phone.
2018-04-22 12:18:29,145 [Level 99]: plugins.blueset.wechat.WeChatChannel (__init__.console_qr_code; __init__.py:206) 
    Successfully logged in.
Loading the contact, this may take a little while.
2018-04-22 12:18:29,145 [INFO]: itchat (login.login; login.py:70) 
    Loading the contact, this may take a little while.
Login successfully as 
2018-04-22 12:18:29,206 [INFO]: itchat (login.login; login.py:80) 
    Login successfully as 
2018-04-22 12:18:29,212 [Level 99]: ehforwarderbot.__main__ (__main__.init; __main__.py:87) 
     Slave channel WeChat Slave (blueset.wechat) # None is initialized. 
2018-04-22 12:18:29,212 [Level 99]: ehforwarderbot.__main__ (__main__.init; __main__.py:90) 
     Initializing master blueset.telegram... 
Traceback (most recent call last):
  File "/usr/local/bin/ehforwarderbot", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/ehforwarderbot/__main__.py", line 190, in main
    init()
  File "/usr/local/lib/python3.6/site-packages/ehforwarderbot/__main__.py", line 94, in init
    (instance_id=instance_id))
  File "/usr/local/lib/python3.6/site-packages/efb_telegram_master/__init__.py", line 124, in __init__
    self.db: DatabaseManager = DatabaseManager(self)
  File "/usr/local/lib/python3.6/site-packages/efb_telegram_master/db.py", line 20, in __init__
    self.db.connect()
  File "/usr/local/lib/python3.6/site-packages/peewee.py", line 2505, in connect
    self._state.set_connection(self._connect())
  File "/usr/local/lib/python3.6/site-packages/peewee.py", line 2737, in _connect
    raise ImproperlyConfigured('SQLite driver not installed!')
peewee.ImproperlyConfigured: SQLite driver not installed!
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/site-packages/itchat/components/login.py", line 281, in maintain_loop
    exitCallback()
  File "/usr/local/lib/python3.6/site-packages/efb_wechat_slave/__init__.py", line 286, in exit_callback
    coordinator.send_message(msg)
  File "/usr/local/lib/python3.6/site-packages/ehforwarderbot/coordinator.py", line 103, in send_message
    msg.verify()
  File "/usr/local/lib/python3.6/site-packages/ehforwarderbot/message.py", line 128, in verify
    raise ValueError("Deliver_to is not valid.")
**ValueError: Deliver_to is not valid.**

```

## Environment:

**1. System:**

 `Linux VM-68-189-ubuntu 4.14.11-041411-generic #201801022143 SMP Tue Jan 2 21:44:21 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

**2. Software version:** 
```
EH Forwarder Bot
Version: 2.0.0b10
Python version:
3.6.1 (default, Apr 22 2018, 09:34:19) 
[GCC 5.4.0 20160609]

Master channel:
    Telegram Master (blueset.telegram) 2.0.0b11 # Default profile

Slave channel:
    WeChat Slave (blueset.wechat) 2.0.0a12

Middlewares:
    No middleware is enabled.
```

## Additional information(config files):

- **~/.ehforwarderbot/profiles/default/config.yaml**

```
master_channel: blueset.telegram
slave_channels:
- blueset.wechat
```

- **~/.ehforwarderbot/profiles/default/blueset.telegram/config.yaml**

```
token: "AAAAAAAAAAAAAAA:AAAAAAAAAAAAAAA"
admins:
- 111111111

# API tokens required for speech recognition
speech_api:
    # https://azure.microsoft.com/en-us/try/cognitive-services/
    bing: "VOICE_RECOGNITION_TOKEN"
    # http://yuyin.baidu.com/
    baidu:
        app_id: 1111111
        api_key: "AAAAAAAAAAAAAAA"
        secret_key: "AAAAAAAAAAAAAAA"


# Experimental Flags
flags:
    no_conversion: false
```

- **~/.ehforwarderbot/profiles/default/blueset.wechat/config.yaml**

```
flags:
    delete_on_edit: true
```

Thanks for your extraordinary work, @blueset . 
Best.

_Copied from original issue: blueset/efb-telegram-master#16_

**Comment by blueset** [comment]
Thanks for the bug report in detail. In your error log, there is a log saying 

> `peewee.ImproperlyConfigured: SQLite driver not installed!`

You may want to check if you have SQLite support installed with your Python 3 installation.

Also another bug is found in the log and fixed which is not directly related to the breakdown.
