### ISSUE TITLE
某个微信账号无法登陆

### ISSUE THREAD

**Issue by fleeto** [blueset/efb-wechat-slave#25]
### 版本信息

```
EH Forwarder Bot
Version: 2.0.0b10
Python version:
3.6.3 (default, Nov 21 2017, 14:55:19)
[GCC 6.4.0]

Master channel:
    Telegram Master (blueset.telegram) 2.0.0b11 # Default profile

Slave channel:
    WeChat Slave (blueset.wechat) 2.0.0a12

Middlewares:
    No middleware is enabled.
```

### 问题描述

- 发现一个微信号掉线
- TG 内出现信息
```
`WS User Auth:
WeChat server has logged you out. Please log in again when you are ready.
--------
Preparing to log in...
```
以及二维码，手机确认操作后，TG 回应 `QR code expired, please scan the new one.`，然后是 `Confirm on your phone.`

- 登录主机重启，应用出错，当时没记录日志。
- 删除 `./blueset.wechat/` 所有文件，删除blueset.telegram/tgdata.db 并重建，带 `-v` 启动应用，得到下面的日志。

**同时使用的另外一个账号无此故障**

### Verbose 日志
<details>
<summary>Verbose 日志</summary>

```
ehforwarderbot -v
2018-06-07 04:03:29,345 [Level 99]: ehforwarderbot.__main__ (__main__.init; __main__.py:77)
     Initializing slave blueset.wechat...
Traceback (most recent call last):
  File "/usr/bin/ehforwarderbot", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python3.6/site-packages/ehforwarderbot/__main__.py", line 190, in main
    init()
  File "/usr/lib/python3.6/site-packages/ehforwarderbot/__main__.py", line 82, in init
    coordinator.add_channel(cls(instance_id=instance_id))
  File "/usr/lib/python3.6/site-packages/efb_wechat_slave/__init__.py", line 174, in __init__
    self.authenticate('console_qr_code')
  File "/usr/lib/python3.6/site-packages/efb_wechat_slave/__init__.py", line 518, in authenticate
    logout_callback=self.exit_callback)
  File "/usr/lib/python3.6/site-packages/efb_wechat_slave/wxpy/api/bot.py", line 86, in __init__
    loginCallback=login_callback, exitCallback=logout_callback
  File "/usr/lib/python3.6/site-packages/itchat/components/register.py", line 29, in auto_login
    loginCallback=loginCallback, exitCallback=exitCallback):
  File "/usr/lib/python3.6/site-packages/itchat/components/hotreload.py", line 54, in load_login_status
    self.loginInfo['User'] = templates.User(self.loginInfo['User'])
KeyError: 'User'
```
 
</details>

**Comment by fleeto** [comment]
补充一下重新配置得到的错误信息

```
If the QR code was not shown correctly, please visit:
https://login.weixin.qq.com/qrcode/XXXX
Traceback (most recent call last):
  File "/usr/bin/ehforwarderbot", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python3.6/site-packages/ehforwarderbot/__main__.py", line 190, in main
    init()
  File "/usr/lib/python3.6/site-packages/ehforwarderbot/__main__.py", line 82, in init
    coordinator.add_channel(cls(instance_id=instance_id))
  File "/usr/lib/python3.6/site-packages/efb_wechat_slave/__init__.py", line 174, in __init__
    self.authenticate('console_qr_code')
  File "/usr/lib/python3.6/site-packages/efb_wechat_slave/__init__.py", line 518, in authenticate
    logout_callback=self.exit_callback)
  File "/usr/lib/python3.6/site-packages/efb_wechat_slave/wxpy/api/bot.py", line 96, in __init__
    enhance_webwx_request(self)
  File "/usr/lib/python3.6/site-packages/efb_wechat_slave/wxpy/utils/misc.py", line 327, in enhance_webwx_request
    '&pass_ticket={li[pass_ticket]}'.format(li=login_info)
KeyError: 'wxsid'
```

**Comment by fleeto** [comment]
login_info 我用 json.dumps 出来看了一下：

```json
{
  "url": "https://wx2.qq.com/cgi-bin/mmwebwx-bin",
  "fileUrl": "https://file.wx2.qq.com/cgi-bin/mmwebwx-bin",
  "syncUrl": "https://webpush.wx2.qq.com/cgi-bin/mmwebwx-bin",
  "deviceid": "abcded",
  "BaseRequest": {}
}
```

**Comment by blueset** [comment]
No relevant report on this issue in the last year. Regarding this as a Web WeChat server-side glitch. Marking this issue as stale and closing as this is out of date.

**Comment by dangfan** [comment]
I met the same KeyError.

```
Traceback (most recent call last):
  File "/usr/local/bin/ehforwarderbot", line 11, in <module>
    load_entry_point('ehforwarderbot==2.0.0b20.dev6', 'console_scripts', 'ehforwarderbot')()
  File "/usr/local/lib/python3.6/site-packages/ehforwarderbot/__main__.py", line 269, in main
    init(conf)
  File "/usr/local/lib/python3.6/site-packages/ehforwarderbot/__main__.py", line 91, in init
    coordinator.add_channel(cls(instance_id=instance_id))
  File "/usr/local/lib/python3.6/site-packages/efb_wechat_slave/__init__.py", line 151, in __init__
    self.authenticate('console_qr_code')
  File "/usr/local/lib/python3.6/site-packages/efb_wechat_slave/__init__.py", line 535, in authenticate
    logout_callback=self.exit_callback)
  File "/usr/local/lib/python3.6/site-packages/efb_wechat_slave/vendor/wxpy/api/bot.py", line 97, in __init__
    enhance_webwx_request(self)
  File "/usr/local/lib/python3.6/site-packages/efb_wechat_slave/vendor/wxpy/utils/misc.py", line 327, in enhance_webwx_request
    '&pass_ticket={li[pass_ticket]}'.format(li=login_info)
KeyError: 'wxsid'
```

**Comment by yi-ji** [comment]
Same errors happened when I tried to scan WeChat login QR code
```Traceback (most recent call last):
  File "/home/ec2-user/.local/bin/ehforwarderbot", line 11, in <module>
    sys.exit(main())
  File "/home/ec2-user/.local/lib/python3.7/site-packages/ehforwarderbot/__main__.py", line 267, in main
    init(conf)
  File "/home/ec2-user/.local/lib/python3.7/site-packages/ehforwarderbot/__main__.py", line 91, in init
    coordinator.add_channel(cls(instance_id=instance_id))
  File "/home/ec2-user/.local/lib/python3.7/site-packages/efb_wechat_slave/__init__.py", line 174, in __init__
    self.authenticate('console_qr_code')
  File "/home/ec2-user/.local/lib/python3.7/site-packages/efb_wechat_slave/__init__.py", line 521, in authenticate
    logout_callback=self.exit_callback)
  File "/home/ec2-user/.local/lib/python3.7/site-packages/efb_wechat_slave/wxpy/api/bot.py", line 97, in __init__
    enhance_webwx_request(self)
  File "/home/ec2-user/.local/lib/python3.7/site-packages/efb_wechat_slave/wxpy/utils/misc.py", line 327, in enhance_webwx_request
    '&pass_ticket={li[pass_ticket]}'.format(li=login_info)
KeyError: 'wxsid'```

**Comment by yi-ji** [comment]
It seems that all WeChat account registered by non-CN phone number without ID verified will encounter this problem. Damn Tencent
