### ISSUE TITLE
Failed to load the contact

### ISSUE THREAD

**Issue by cxumol** [blueset/efb-wechat-slave#35]
### 版本信息

EH Forwarder Bot
Version: 2.0.0b11
Python version:
3.6.2 |Continuum Analytics, Inc.| (default, Jul 20 2017, 13:51:32)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]

Master channel:
    Telegram Master (blueset.telegram) 2.0.0b12 # Default profile

Slave channel:
    WeChat Slave (blueset.wechat) 2.0.0a13 # Default profile

Middlewares:
    No middleware is enabled.

### 问题描述

—> 扫码登陆微信
—> EFB log 和 手机微信均显示成功登陆网页版, 然后 EFB 显示解析联系人失败
—> 重启扫码重试, 同样错误
—> 删掉 ~/.ehforwarderbot/profiles/default/blueset.wechat/* 重试, 同样错误
—> 换梯子重试, 同样错误

### 重现步骤

EFB 掉线 (tg端无提示) 后, 重启, 扫码登陆后出现此状况｡   
重现步骤未知

### Verbose 日志
<details>
<summary>Verbose 日志</summary>

```
Please scan the QR code to log in.
2018-10-26 08:13:31,000 [Level 99]: plugins.blueset.wechat.WeChatChannel (__init__.console_qr_code; __init__.py:203)
    Confirm on your phone.
Please press confirm on your phone.
2018-10-26 08:13:33,917 [Level 99]: plugins.blueset.wechat.WeChatChannel (__init__.console_qr_code; __init__.py:206)
    Successfully logged in.
Loading the contact, this may take a little while.
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/bin/ehforwarderbot", line 11, in <module>
    sys.exit(main())
  File "/home/ubuntu/miniconda3/lib/python3.6/site-packages/ehforwarderbot/__main__.py", line 202, in main
    init()
  File "/home/ubuntu/miniconda3/lib/python3.6/site-packages/ehforwarderbot/__main__.py", line 83, in init
    coordinator.add_channel(cls(instance_id=instance_id))
  File "/home/ubuntu/miniconda3/lib/python3.6/site-packages/efb_wechat_slave/__init__.py", line 174, in __init__
    self.authenticate('console_qr_code')
  File "/home/ubuntu/miniconda3/lib/python3.6/site-packages/efb_wechat_slave/__init__.py", line 519, in authenticate
    logout_callback=self.exit_callback)
  File "/home/ubuntu/miniconda3/lib/python3.6/site-packages/efb_wechat_slave/wxpy/api/bot.py", line 86, in __init__
    loginCallback=login_callback, exitCallback=logout_callback
  File "/home/ubuntu/miniconda3/lib/python3.6/site-packages/itchat/components/register.py", line 32, in auto_login
    loginCallback=loginCallback, exitCallback=exitCallback)
  File "/home/ubuntu/miniconda3/lib/python3.6/site-packages/itchat/components/login.py", line 73, in login
    self.get_contact(True)
  File "/home/ubuntu/miniconda3/lib/python3.6/site-packages/itchat/components/contact.py", line 285, in get_contact
    seq, batchMemberList = _get_contact(seq)
  File "/home/ubuntu/miniconda3/lib/python3.6/site-packages/itchat/components/contact.py", line 281, in _get_contact
    j = json.loads(r.content.decode('utf-8', 'replace'))
  File "/home/ubuntu/miniconda3/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/home/ubuntu/miniconda3/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/ubuntu/miniconda3/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

```
请在这里贴出您的 Verbose 日志。如果您对隐私有所顾虑，您可以自行
隐去隐私信息、或 GPG 加密至 BD6B65EC00638DC9083781D5D4B65BB1A106200A。



```
 
</details>

**Comment by blueset** [comment]
This issue has been marked as stale and closed because it has not had recent activity. Thank you  for your contributions.
