### ISSUE TITLE
微信群值被@时不能正常显示消息

### ISSUE THREAD

**Issue by code-n00b** [blueset/efb-wechat-slave#37]
### 版本信息
EH Forwarder Bot
Version: 2.0.0b11
Python version:
3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0]

Master channel:
    Telegram Master (blueset.telegram) 2.0.0b13 # Default profile

Slave channel:
    WeChat Slave (blueset.wechat) 2.0.0a13 # Default profile

Middlewares:
    No middleware is enabled.

### 问题描述
被@时不正常显示信息  
="tg://user?id=123">=&quot;tg:</a>

### 重现步骤
微信群内被@时出现

### Verbose 日志  
<details>
<summary>Verbose 日志</summary>

2018-11-23 01:59:28,104 [Level 99]: ehforwarderbot.__main__ (__main__.init; __main__.py:91)
     Initializing master blueset.telegram...   

2018-11-23 01:59:28,718 [ERROR]: efb_wechat_slave.wxpy.api.bot (bot.process; bot.py:457)
    an error occurred in <bound method SlaveMessageManager.Decorators.wechat_msg_meta.<locals>.thread_wrapper of <efb_wechat_slave.slave_message.SlaveMessageManager object at 0x7f3046a63a58>>.  

Traceback (most recent call last):  

  File "/usr/local/lib/python3.6/dist-packages/efb_wechat_slave/wxpy/api/bot.py", line 453, in process
    ret = config.func(msg)  

  File "/usr/local/lib/python3.6/dist-packages/efb_wechat_slave/slave_message.py", line 78, in thread_wrapper  
    threading.Thread(target=wrap_func, args=args, kwargs=kwargs).run()  

  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)  

  File "/usr/local/lib/python3.6/dist-packages/efb_wechat_slave/slave_message.py", line 72, in wrap_func
    coordinator.send_message(efb_msg)  

  File "/usr/local/lib/python3.6/dist-packages/ehforwarderbot/coordinator.py", line 103, in send_message
    msg.verify()  

  File "/usr/local/lib/python3.6/dist-packages/ehforwarderbot/message.py", line 128, in verify
    raise ValueError("Deliver_to is not valid.")  

ValueError: Deliver_to is not valid.  

2018-11-23 01:59:29,264 [Level 99]: ehforwarderbot.__main__ (__main__.init; __main__.py:100)
     Master channel Telegram Master (blueset.telegram) # Default profile is initialized.   
                                                                      
2018-11-23 01:59:29,264 [Level 99]: ehforwarderbot.__main__ (__main__.init; __main__.py:102)
     All channels initialized.   

2018-11-23 01:59:29,265 [Level 99]: ehforwarderbot.__main__ (__main__.init; __main__.py:115)
     All middlewares are initialized.   

</details>

**Comment by code-n00b** [comment]
[fixed?](https://github.com/blueset/efb-telegram-master/commit/83ceec51a588e9cbcf544714ad85efc4fedf2b9c#diff-b8a40db58695838e44f61036f5822dce)
