### ISSUE TITLE
不转发定位信息

### ISSUE THREAD

**Issue by GoGoogle** [blueset/efb-wechat-slave#44]
### 版本信息

EH Forwarder Bot
Version: 2.0.0b14
Python version:
3.7.2rc1 (default, Dec 18 2018, 15:59:07) 
[GCC 6.3.0 20170516]

Master channel:
    Telegram Master (blueset.telegram) 2.0.0b18 # Default instance

Slave channel:
    WeChat Slave (blueset.wechat) 2.0.0a17 # Default instance

Middlewares:
    No middleware is enabled.

### 问题描述

WEB版本在WEB上是可以正常接收定位信息的，但EFB是没有任何信息显示的。

### 重现步骤

百试百灵。

### Verbose 日志
<details>
<summary>Verbose 日志</summary>

```
UserName: @1234567890
NickName: 2.隔壁老王
Type: MsgType.Text
Text: 发了吗？不管发没发，再发一条
2019-03-11 13:06:43,850 [DEBUG]: efb_wechat_slave.wxpy.api.chats.chat (chat.mark_as_read; chat.py:291)
    marking <Friend: 2.隔壁老王> as read
2019-03-11 13:06:43,944 [DEBUG]: plugins.blueset.wechat.WeChatChannel (__init__.send_message; __init__.py:325)
    [-448561906.72146] Is edited: False
2019-03-11 13:06:43,944 [INFO]: efb_wechat_slave.wxpy.api.chats.chat (chat.wrapped; chat.py:47)
    sending msg to <Friend: 2.隔壁老王>:
发了吗？不管发没发，再发一条
2019-03-11 13:06:43,945 [DEBUG]: itchat (messages.send_msg; messages.py:282)
    Request to send a text message to @1234567890: 发了吗？不管发没发，再发一条
2019-03-11 13:06:44,082 [DEBUG]: plugins.blueset.wechat.WeChatChannel (__init__.send_message; __init__.py:354)
    [-448561906.72146] Sent as a text message. 发了吗？不管发没发，再发一条
2019-03-11 13:06:44,082 [DEBUG]: plugins.blueset.wechat.WeChatChannel (__init__.send_message; __init__.py:400)
    WeChat message is assigned with unique ID: c7cc8271 3735837194999480574 15522808039464
2019-03-11 13:06:44,084 [DEBUG]: peewee (peewee.execute_sql; peewee.py:2699)
    ('INSERT INTO "msglog" ("master_msg_id", "master_msg_id_alt", "slave_message_id", "text", "slave_origin_uid", "slave_origin_display_name", "slave_member_uid", "slave_member_display_name", "media_type", "mime", "file_id", "msg_type", "sent_to", "time") VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)', ['-448561906.72146', None, 'c7cc8271 3735837194999480574 15522808039464', '发了吗？不管发没发，再发一条', 'blueset.wechat c7cc8271', '__chat__', None, None, None, None, None, 'MsgType.Text', 'slave', datetime.datetime(2019, 3, 11, 13, 6, 44, 83657)])
2019-03-11 13:06:58,866 [DEBUG]: efb_wechat_slave.wxpy.api.bot (bot._process_message; bot.py:448)
    <Bot: !老王隔壁>: new message (func: thread_wrapper):
2.隔壁老王 : 某XX公司(NN路) (Map)
2019-03-11 13:06:59,033 [DEBUG]: efb_wechat_slave.wxpy.api.bot (misc.start_new_thread; misc.py:421)
    new thread: _process_message
2019-03-11 13:06:59,034 [DEBUG]: efb_wechat_slave.slave_message (slave_message.wrap_func; slave_message.py:51)
    [9070053242263850773] Raw message: <Message: {'MsgId': '9070053242263850773', 'FromUserName': '@1234567890', 'ToUserName': '@911', 'MsgType': 1, 'Content': '某XX公司(NN路):\n/cgi-bin/mmwebwx-bin/webwxgetpubliclinkimg?url=xxx&msgid=9070053242263850773&pictype=location', 'Status': 3, 'ImgStatus': 1, 'CreateTime': 1552280815, 'VoiceLength': 0, 'PlayLength': 0, 'FileName': '', 'FileSize': '', 'MediaId': '', 'Url': 'http://apis.map.qq.com/uri/v1/geocoder?coord=纬度,经度', 'AppMsgType': 0, 'StatusNotifyCode': 0, 'StatusNotifyUserName': '', 'RecommendInfo': {'UserName': '', 'NickName': '', 'QQNum': 0, 'Province': '', 'City': '', 'Content': '', 'Signature': '', 'Alias': '', 'Scene': 0, 'VerifyFlag': 0, 'AttrStatus': 0, 'Sex': 0, 'Ticket': '', 'OpCode': 0}, 'ForwardFlag': 0, 'AppInfo': {'AppID': '', 'Type': 0}, 'HasProductId': 0, 'Ticket': '', 'ImgHeight': 0, 'ImgWidth': 0, 'SubMsgType': 48, 'NewMsgId': 9070053242263850773, 'OriContent': '<?xml version="1.0"?>\n<msg>\n\t<location x="纬度" y="经度" scale="16" label="某XX公司(NN路)" maptype="0" poiname="[位置]" poiid="" />\n</msg>\n', 'EncryFileName': '', 'User': <User: {'MemberList': <ContactList: []>, 'Uin': 0, 'UserName': '@1234567890', 'NickName': 'PP', 'HeadImgUrl': '/cgi-bin/mmwebwx-bin/webwxgeticon?seq=667451132&username=@1234567890&skey=@crypt_55c0934b_adf2dd3991dad56d90944cb24989899e', 'ContactFlag': 3, 'MemberCount': 0, 'RemarkName': '2.隔壁老王', 'HideInputBarFlag': 0, 'Sex': 1, 'Signature': '', 'VerifyFlag': 0, 'OwnerUin': 0, 'PYInitial': 'P', 'PYQuanPin': 'peng', 'RemarkPYInitial': '2WP', 'RemarkPYQuanPin': '2wangpeng', 'StarFriend': 0, 'AppAccountFlag': 0, 'Statues': 0, 'AttrStatus': 17018981, 'Province': '', 'City': '', 'Alias': '', 'SnsFlag': 17, 'UniFriend': 0, 'DisplayName': '', 'ChatRoomId': 0, 'KeyWord': '', 'EncryChatRoomId': '', 'IsOwner': 0}>, 'Type': 'Map', 'Text': '某XX公司(NN路)'}>
2019-03-11 13:06:59,037 [DEBUG]: efb_wechat_slave.chats (chats.wxpy_chat_to_efb_chat; chats.py:67)
    Converting WXPY chat <Friend: 2.隔壁老王>, in recursive mode
2019-03-11 13:06:59,038 [DEBUG]: efb_wechat_slave.chats (chats.wxpy_chat_to_efb_chat; chats.py:68)
    WXPY chat with ID: c7cc8271, name: PP, alias: ;
2019-03-11 13:06:59,039 [DEBUG]: efb_wechat_slave.chats (chats.wxpy_chat_to_efb_chat; chats.py:96)
    [WXPY: c7cc8271] Remark name: 2.隔壁老王;
2019-03-11 13:06:59,040 [DEBUG]: efb_wechat_slave.chats (chats.wxpy_chat_to_efb_chat; chats.py:102)
    WXPY chat c7cc8271 converted to EFBChat <EFBChat: PP (2.隔壁老王, c7cc8271) @ WeChat Slave>
2019-03-11 13:06:59,042 [DEBUG]: efb_wechat_slave.chats (chats.wxpy_chat_to_efb_chat; chats.py:67)
    Converting WXPY chat <Friend: 2.隔壁老王>, in recursive mode
2019-03-11 13:06:59,042 [DEBUG]: efb_wechat_slave.chats (chats.wxpy_chat_to_efb_chat; chats.py:68)
    WXPY chat with ID: c7cc8271, name: PP, alias: ;
2019-03-11 13:06:59,043 [DEBUG]: efb_wechat_slave.chats (chats.wxpy_chat_to_efb_chat; chats.py:96)
    [WXPY: c7cc8271] Remark name: 2.隔壁老王;
2019-03-11 13:06:59,044 [DEBUG]: efb_wechat_slave.chats (chats.wxpy_chat_to_efb_chat; chats.py:102)
    WXPY chat c7cc8271 converted to EFBChat <EFBChat: PP (2.隔壁老王, c7cc8271) @ WeChat Slave>
2019-03-11 13:06:59,045 [DEBUG]: efb_wechat_slave.slave_message (slave_message.wrap_func; slave_message.py:68)
    [9070053242263850773] Chat: <EFBChat: PP (2.隔壁老王, c7cc8271) @ WeChat Slave>, Author: <EFBChat: PP (2.隔壁老王, c7cc8271) @ WeChat Slave>
2019-03-11 13:06:59,045 [DEBUG]: efb_telegram_master.slave_message (slave_message.send_message; slave_message.py:53)
    [9070053242263850773] Slave message delivered to ETM.
<EFBMsg, <EFBChat: PP (2.隔壁老王, c7cc8271) @ WeChat Slave>@<EFBChat: PP (2.隔壁老王, c7cc8271) @ WeChat Slave> [Location]: 某XX公司(NN路; 9070053242263850773>
2019-03-11 13:06:59,047 [DEBUG]: peewee (peewee.execute_sql; peewee.py:2699)
    ('SELECT "t1"."id", "t1"."master_uid", "t1"."slave_uid" FROM "chatassoc" AS "t1" WHERE ("t1"."slave_uid" = ?)', ['blueset.wechat c7cc8271'])
2019-03-11 13:06:59,049 [DEBUG]: efb_telegram_master.slave_message (slave_message.send_message; slave_message.py:60)
    [9070053242263850773] The message should deliver to blueset.telegram -448561906
2019-03-11 13:06:59,050 [DEBUG]: peewee (peewee.execute_sql; peewee.py:2699)
    ('SELECT "t1"."id", "t1"."master_uid", "t1"."slave_uid" FROM "chatassoc" AS "t1" WHERE ("t1"."master_uid" = ?)', ['blueset.telegram -448561906'])
2019-03-11 13:06:59,051 [DEBUG]: efb_telegram_master.slave_message (slave_message.send_message; slave_message.py:74)
    [9070053242263850773] Message is in chat <EFBChat: PP (2.隔壁老王, c7cc8271) @ WeChat Slave>
2019-03-11 13:06:59,052 [DEBUG]: efb_telegram_master.slave_message (slave_message.send_message; slave_message.py:84)
    [9070053242263850773] Message is sent to Telegram chat -448561906, with header "".
2019-03-11 13:07:01,099 [INFO]: efb_telegram_master.slave_message (slave_message.slave_message_location; slave_message.py:458)
    [9070053242263850773] Sending as a Telegram venue.
lat: 纬度, long: 经度
title: 某XX公司(NN路
address: 
2019-03-11 13:07:01,117 [ERROR]: efb_telegram_master.slave_message (slave_message.send_message; slave_message.py:208)
    [9070053242263850773] Error occurred while processing message from slave channel.
Message: <EFBMsg, <EFBChat: PP (2.隔壁老王, c7cc8271) @ WeChat Slave>@<EFBChat: PP (2.隔壁老王, c7cc8271) @ WeChat Slave> [Location]: 某XX公司(NN路; Attributes: <EFBMsgLocationAttribute: 纬度,经度>; Delivering to: <efb_telegram_master.TelegramChannel object at 0x7fbdd9933ac8>; Edited: False; System message: False; Substitutions: None; Target messages: None; UID: 9070053242263850773; Reactions: {}; File: None (None @ None), None; Vendor: {}>
ValueError('Either venue or latitude, longitude, address and title must bepassed as arguments.')
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/efb_telegram_master/slave_message.py", line 147, in send_message
    reply_markup)
  File "/usr/local/lib/python3.7/site-packages/efb_telegram_master/slave_message.py", line 466, in slave_message_location
    reply_markup=reply_markup)
  File "/usr/local/lib/python3.7/site-packages/efb_telegram_master/bot_manager.py", line 368, in send_venue
    return self.updater.bot.send_venue(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/telegram/bot.py", line 65, in decorator
    result = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/telegram/bot.py", line 76, in decorator
    url, data = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/telegram/bot.py", line 1211, in send_venue
    raise ValueError("Either venue or latitude, longitude, address and title must be"
ValueError: Either venue or latitude, longitude, address and title must bepassed as arguments.

2019-03-11 13:07:06,182 [DEBUG]: efb_wechat_slave.wxpy.api.bot (bot._process_message; bot.py:448)
    <Bot: !老王隔壁>: new message (func: thread_wrapper):
2.隔壁老王 : 收不到？ (Text)
2019-03-11 13:07:06,187 [DEBUG]: efb_wechat_slave.wxpy.api.bot (misc.start_new_thread; misc.py:421)
    new thread: _process_message
2019-03-11 13:07:06,188 [DEBUG]: efb_wechat_slave.slave_message (slave_message.wrap_func; slave_message.py:51)
    [7525258192477748099] Raw message: <Message: {'MsgId': '7525258192477748099', 'FromUserName': '@1234567890', 'ToUserName': '@911', 'MsgType': 1, 'Content': '收不到？', 'Status': 3, 'ImgStatus': 1, 'CreateTime': 1552280823, 'VoiceLength': 0, 'PlayLength': 0, 'FileName': '', 'FileSize': '', 'MediaId': '', 'Url': '', 'AppMsgType': 0, 'StatusNotifyCode': 0, 'StatusNotifyUserName': '', 'RecommendInfo': {'UserName': '', 'NickName': '', 'QQNum': 0, 'Province': '', 'City': '', 'Content': '', 'Signature': '', 'Alias': '', 'Scene': 0, 'VerifyFlag': 0, 'AttrStatus': 0, 'Sex': 0, 'Ticket': '', 'OpCode': 0}, 'ForwardFlag': 0, 'AppInfo': {'AppID': '', 'Type': 0}, 'HasProductId': 0, 'Ticket': '', 'ImgHeight': 0, 'ImgWidth': 0, 'SubMsgType': 0, 'NewMsgId': 7525258192477748099, 'OriContent': '', 'EncryFileName': '', 'User': <User: {'MemberList': <ContactList: []>, 'Uin': 0, 'UserName': '@1234567890', 'NickName': 'PP', 'HeadImgUrl': '/cgi-bin/mmwebwx-bin/webwxgeticon?seq=667451132&username=@1234567890&skey=@crypt_55c0934b_adf2dd3991dad56d90944cb24989899e', 'ContactFlag': 3, 'MemberCount': 0, 'RemarkName': '2.隔壁老王', 'HideInputBarFlag': 0, 'Sex': 1, 'Signature': '', 'VerifyFlag': 0, 'OwnerUin': 0, 'PYInitial': 'P', 'PYQuanPin': 'peng', 'RemarkPYInitial': '2WP', 'RemarkPYQuanPin': '2wangpeng', 'StarFriend': 0, 'AppAccountFlag': 0, 'Statues': 0, 'AttrStatus': 17018981, 'Province': '', 'City': '', 'Alias': '', 'SnsFlag': 17, 'UniFriend': 0, 'DisplayName': '', 'ChatRoomId': 0, 'KeyWord': '', 'EncryChatRoomId': '', 'IsOwner': 0}>, 'Type': 'Text', 'Text': '收不到？'}>
2019-03-11 13:07:06,191 [DEBUG]: itchat (messagequeue.__getitem__; messagequeue.py:24)
    isAt is expired in 1.3.0, use IsAt instead.
2019-03-11 13:07:06,192 [DEBUG]: efb_wechat_slave.chats (chats.wxpy_chat_to_efb_chat; chats.py:67)
    Converting WXPY chat <Friend: 2.隔壁老王>, in recursive mode
2019-03-11 13:07:06,193 [DEBUG]: efb_wechat_slave.chats (chats.wxpy_chat_to_efb_chat; chats.py:68)
    WXPY chat with ID: c7cc8271, name: PP, alias: ;
2019-03-11 13:07:06,193 [DEBUG]: efb_wechat_slave.chats (chats.wxpy_chat_to_efb_chat; chats.py:96)
    [WXPY: c7cc8271] Remark name: 2.隔壁老王;
2019-03-11 13:07:06,194 [DEBUG]: efb_wechat_slave.chats (chats.wxpy_chat_to_efb_chat; chats.py:102)
    WXPY chat c7cc8271 converted to EFBChat <EFBChat: PP (2.隔壁老王, c7cc8271) @ WeChat Slave>
2019-03-11 13:07:06,196 [DEBUG]: efb_wechat_slave.chats (chats.wxpy_chat_to_efb_chat; chats.py:67)
    Converting WXPY chat <Friend: 2.隔壁老王>, in recursive mode
2019-03-11 13:07:06,197 [DEBUG]: efb_wechat_slave.chats (chats.wxpy_chat_to_efb_chat; chats.py:68)
    WXPY chat with ID: c7cc8271, name: PP, alias: ;
2019-03-11 13:07:06,198 [DEBUG]: efb_wechat_slave.chats (chats.wxpy_chat_to_efb_chat; chats.py:96)
    [WXPY: c7cc8271] Remark name: 2.隔壁老王;
2019-03-11 13:07:06,198 [DEBUG]: efb_wechat_slave.chats (chats.wxpy_chat_to_efb_chat; chats.py:102)
    WXPY chat c7cc8271 converted to EFBChat <EFBChat: PP (2.隔壁老王, c7cc8271) @ WeChat Slave>
2019-03-11 13:07:06,199 [DEBUG]: efb_wechat_slave.slave_message (slave_message.wrap_func; slave_message.py:68)
    [7525258192477748099] Chat: <EFBChat: PP (2.隔壁老王, c7cc8271) @ WeChat Slave>, Author: <EFBChat: PP (2.隔壁老王, c7cc8271) @ WeChat Slave>
2019-03-11 13:07:06,200 [DEBUG]: efb_telegram_master.slave_message (slave_message.send_message; slave_message.py:53)
    [7525258192477748099] Slave message delivered to ETM.
<EFBMsg, <EFBChat: PP (2.隔壁老王, c7cc8271) @ WeChat Slave>@<EFBChat: PP (2.隔壁老王, c7cc8271) @ WeChat Slave> [Text]: 收不到？; 7525258192477748099>
2019-03-11 13:07:06,201 [DEBUG]: peewee (peewee.execute_sql; peewee.py:2699)
    ('SELECT "t1"."id", "t1"."master_uid", "t1"."slave_uid" FROM "chatassoc" AS "t1" WHERE ("t1"."slave_uid" = ?)', ['blueset.wechat c7cc8271'])
2019-03-11 13:07:06,203 [DEBUG]: efb_telegram_master.slave_message (slave_message.send_message; slave_message.py:60)
    [7525258192477748099] The message should deliver to blueset.telegram -448561906
2019-03-11 13:07:06,205 [DEBUG]: peewee (peewee.execute_sql; peewee.py:2699)
    ('SELECT "t1"."id", "t1"."master_uid", "t1"."slave_uid" FROM "chatassoc" AS "t1" WHERE ("t1"."master_uid" = ?)', ['blueset.telegram -448561906'])
2019-03-11 13:07:06,206 [DEBUG]: efb_telegram_master.slave_message (slave_message.send_message; slave_message.py:74)
    [7525258192477748099] Message is in chat <EFBChat: PP (2.隔壁老王, c7cc8271) @ WeChat Slave>
2019-03-11 13:07:06,207 [DEBUG]: efb_telegram_master.slave_message (slave_message.send_message; slave_message.py:84)
    [7525258192477748099] Message is sent to Telegram chat -448561906, with header "".
2019-03-11 13:07:06,207 [DEBUG]: efb_telegram_master.slave_message (slave_message.slave_message_text; slave_message.py:228)
    [7525258192477748099] Sending as a text message.
2019-03-11 13:07:07,707 [DEBUG]: efb_telegram_master.slave_message (slave_message.slave_message_text; slave_message.py:317)
    [7525258192477748099] Processed and sent as text message
2019-03-11 13:07:07,708 [DEBUG]: efb_telegram_master.slave_message (slave_message.send_message; slave_message.py:164)
    [7525258192477748099] Message is sent to the user with telegram message id -448561906.72147.
2019-03-11 13:07:07,710 [DEBUG]: peewee (peewee.execute_sql; peewee.py:2699)
    ('INSERT INTO "msglog" ("master_msg_id", "master_msg_id_alt", "slave_message_id", "text", "slave_origin_uid", "slave_origin_display_name", "slave_member_uid", "slave_member_display_name", "media_type", "mime", "file_id", "msg_type", "sent_to", "time") VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)', ['-448561906.72147', None, '7525258192477748099', '收不到？', 'blueset.wechat c7cc8271', '2.隔壁老王', 'c7cc8271', '2.隔壁老王', None, None, None, 'MsgType.Text', 'slave', datetime.datetime(2019, 3, 11, 13, 7, 7, 709367)])
2019-03-11 13:07:07,838 [DEBUG]: efb_telegram_master.slave_message (slave_message.send_message; slave_message.py:205)
    [7525258192477748099] Message inserted/updated to the database.
2019-03-11 13:07:19,148 [DEBUG]: telegram.ext.dispatcher (dispatcher.start; dispatcher.py:227)
    Processing Update: {'update_id': 650725682, 'message': {'message_id': 72148, 'date': 1552280836, 'chat': {'id': -448561906, 'type': 'group', 'title': '💬👤 2.隔壁老王', 'all_members_are_administrators': False}, 'text': '收不到，正在调试。好，谢谢。', 'entities': [], 'caption_entities': [], 'photo': [], 'new_chat_members': [], 'new_chat_photo': [], 'delete_chat_photo': False, 'group_chat_created': False, 'supergroup_chat_created': False, 'channel_chat_created': False, 'from': {'id': TGID, 'first_name': '我自己TG名字', 'is_bot': False, 'username': 'ME', 'language_code': 'zh-hans'}}}
2019-03-11 13:07:19,149 [DEBUG]: efb_telegram_master.locale_handler (locale_handler.check_update; locale_handler.py:36)
    [650725682] Update has language zh-hans.
2019-03-11 13:07:19,150 [DEBUG]: efb_telegram_master.master_message (master_message.msg; master_message.py:85)
    Received message from Telegram: {'message_id': 72148, 'date': 1552280836, 'chat': {'id': -448561906, 'type': 'group', 'title': '💬👤 2.隔壁老王', 'all_members_are_administrators': False}, 'text': '收不到，正在调试。好，谢谢。', 'entities': [], 'caption_entities': [], 'photo': [], 'new_chat_members': [], 'new_chat_photo': [], 'delete_chat_photo': False, 'group_chat_created': False, 'supergroup_chat_created': False, 'channel_chat_created': False, 'from': {'id': TGID, 'first_name': '我自己TG名字', 'is_bot': False, 'username': 'ME', 'language_code': 'zh-hans'}}
2019-03-11 13:07:19,152 [DEBUG]: peewee (peewee.execute_sql; peewee.py:2699)
    ('SELECT "t1"."id", "t1"."master_uid", "t1"."slave_uid" FROM "chatassoc" AS "t1" WHERE ("t1"."master_uid" = ?)', ['blueset.telegram -448561906'])
2019-03-11 13:07:19,153 [DEBUG]: efb_telegram_master.master_message (master_message.process_telegram_message; master_message.py:143)
    [-448561906.72148] Message is edited: False, None
2019-03-11 13:07:19,155 [DEBUG]: peewee (peewee.execute_sql; peewee.py:2699)
    ('SELECT "t1"."id", "t1"."master_uid", "t1"."slave_uid" FROM "chatassoc" AS "t1" WHERE ("t1"."master_uid" = ?)', ['blueset.telegram -448561906'])
2019-03-11 13:07:19,156 [DEBUG]: efb_telegram_master.master_message (master_message.process_telegram_message; master_message.py:219)
    [-448561906.72148] Telegram received. From private chat: False; Group has multiple linked chats: False; Message replied to another message: False
2019-03-11 13:07:19,157 [DEBUG]: efb_telegram_master.master_message (master_message.process_telegram_message; master_message.py:220)
    [-448561906.72148] Destination chat = blueset.wechat c7cc8271
2019-03-11 13:07:19,157 [DEBUG]: efb_telegram_master.master_message (master_message.process_telegram_message; master_message.py:257)
    [-448561906.72148] Message type from Telegram: Text
2019-03-11 13:07:19,158 [DEBUG]: efb_telegram_master.master_message (master_message.process_telegram_message; master_message.py:261)
    [-448561906.72148] EFB message type: Text
2019-03-11 13:07:19,175 [INFO]: plugins.blueset.wechat.WeChatChannel (__init__.send_message; __init__.py:321)
    [-448561906.72148] Sending message to WeChat:
uid: c7cc8271
UserName: @1234567890
NickName: 2.隔壁老王
Type: MsgType.Text
Text: 收不到，正在调试。好，谢谢


```
 
</details>

**Comment by GoGoogle** [comment]
#建议 
建议可以使用以下URL来替换http://apis.map.qq.com/uri/v1/geocoder?coord=以达到有效支持手机和电脑打开定位地址
uri.amap.com/marker?position=116.395329,39.922764

**Comment by blueset** [comment]
感谢汇报，已修复。
