### ISSUE TITLE
无法正常接受微信上别人发送的文件

### ISSUE THREAD

**Issue by coffeecaty** [blueset/efb-wechat-slave#45]
### 版本信息

EH Forwarder Bot
Version: 2.0.0b15
Python version:
3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0]

Master channel:
    Telegram Master (blueset.telegram) 2.0.0b20 # Default instance

Slave channel:
    WeChat Slave (blueset.wechat) 2.0.0a18 # Default instance

### 问题描述

别人发送文件telegram上无法收到，服务器端提示错误

2019-04-14 10:22:21,529 [ERROR]: efb_telegram_master.slave_message (slave_message.send_message; slave_message.py:214)
    [8846912686890660079] Error occurred while processing message from slave channel.
Message: <EFBMsg, <EFBChat: You (__self__) @ WeChat Slave>@<EFBChat: 文件传输助手 (filehelper) @ WeChat Slave> [File]: 副本武清六条路疑问单第三版.xlsx; Attributes: None; Delivering to: <efb_telegram_master.TelegramChannel object at 0x7f6d753cbc88>; Edited: False; System message: False; Substitutions: None; Target messages: None; UID: 8846912686890660079; Reactions: {}; File: <tempfile._TemporaryFileWrapper object at 0x7f6d749d9160> (副本武清六条路疑问单第 三版.xlsx @ /tmp/tmpctpyd1qh), application/vnd.openxmlformats-officedocument.spreadsheetml.sheet; Vendor: {}>
BadRequest()
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/efb_telegram_master/slave_message.py", line 149, in send_message
    tg_msg = self.slave_message_file(msg, tg_dest, msg_template, old_msg_id, target_msg_id, reply_markup)
  File "/usr/local/lib/python3.6/dist-packages/efb_telegram_master/slave_message.py", line 418, in slave_message_file
    reply_markup=reply_markup)
  File "/usr/local/lib/python3.6/dist-packages/efb_telegram_master/bot_manager.py", line 230, in caption_affix
    return fn(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/efb_telegram_master/bot_manager.py", line 342, in send_document
    return self.updater.bot.send_document(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/telegram/bot.py", line 65, in decorator
    result = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/telegram/bot.py", line 90, in decorator
    result = self._request.post(url, data, timeout=kwargs.get('timeout'))
  File "/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py", line 305, in post
    result = self._request_wrapper('POST', url, fields=data, **urlopen_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py", line 223, in _request_wrapper
    raise BadRequest(message)
telegram.error.BadRequest: Wrong url host

### Verbose 日志
<details>
<summary>Verbose 日志</summary>

```
请在这里贴出您的 Verbose 日志。如果您对隐私有所顾虑，您可以自行
隐去隐私信息、或 GPG 加密至 BD6B65EC00638DC9083781D5D4B65BB1A106200A。



```
 
</details>

**Comment by coffeecaty** [comment]
2019-04-14 10:59:21,481 [ERROR]: efb_telegram_master.slave_message (slave_message.send_message; slave_message.py:214)
    [6492550962138777592] Error occurred while processing message from slave channel.
Message: <EFBMsg, <EFBChat: You (__self__) @ WeChat Slave>@<EFBChat: 文件传输助手 (filehelper) @ WeChat Slave> [File]: 魔女BLOG初中級日麻講座 .pdf; Attributes: None; Delivering to: <efb_telegram_master.TelegramChannel object at 0x7fa8b8e0ccf8>; Edited: False; System message: False; Substitutions: None; Target messages: None; UID: 6492550962138777592; Reactions: {}; File: <tempfile._TemporaryFileWrapper object at 0x7fa8b8b64cf8> (魔女BLOG初中級日麻講座 .pdf @ /tmp/tmp0yf1abf4), application/pdf; Vendor: {}>
TelegramError()
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py", line 157, in _parse
    data = json.loads(decoded_s)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/efb_telegram_master/slave_message.py", line 149, in send_message
    tg_msg = self.slave_message_file(msg, tg_dest, msg_template, old_msg_id, target_msg_id, reply_markup)
  File "/usr/local/lib/python3.6/dist-packages/efb_telegram_master/slave_message.py", line 418, in slave_message_file
    reply_markup=reply_markup)
  File "/usr/local/lib/python3.6/dist-packages/efb_telegram_master/bot_manager.py", line 230, in caption_affix
    return fn(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/efb_telegram_master/bot_manager.py", line 342, in send_document
    return self.updater.bot.send_document(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/telegram/bot.py", line 65, in decorator
    result = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/telegram/bot.py", line 90, in decorator
    result = self._request.post(url, data, timeout=kwargs.get('timeout'))
  File "/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py", line 305, in post
    result = self._request_wrapper('POST', url, fields=data, **urlopen_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py", line 216, in _request_wrapper
    message = self._parse(resp.data)
  File "/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py", line 163, in _parse
    raise TelegramError('Invalid server response')
telegram.error.TelegramError: Invalid server response



多试了几个文件 发现这种报错比较具有普遍性 上面贴的那个好像只出现过一次

**Comment by blueset** [comment]
已知问题，本 issue 应属于 ETM 仓库。问题由上游库 `python-telegram-bot` 造成。

详情请参阅 [ETM#54](https://github.com/blueset/efb-telegram-master/issues/54)。
