### ISSUE TITLE
EWS 在初始化网络连接失败时返回值为 0

### ISSUE THREAD

**Issue by reallyimeric** [blueset/efb-wechat-slave#50]
### 版本信息

```
EH Forwarder Bot
Version: 2.0.0b15
Python version:
3.7.3 (default, Mar 26 2019, 21:43:19) 
[GCC 8.2.1 20181127]

Master channel:
    Telegram Master (blueset.telegram) 2.0.0b20 # Default instance

Slave channel:
    WeChat Slave (blueset.wechat) 2.0.0a18 # Default instance

Middlewares:
    No middleware is enabled.
```

### 问题描述

无网络时EFB返回值为零

### 重现步骤

1. 断网
2. 启动EFB

### Verbose 日志
<details>
<summary>Verbose 日志</summary>

```
systemd[1]: Started EFB default.
ehforwarderbot[13]: [95B blob data]
ehforwarderbot[13]:      Initializing slave blueset.wechat... 
ehforwarderbot[13]: 2019-05-xx xx:xx:xx,966 [ERROR]: itchat (utils.test_connect; utils.py:129)
ehforwarderbot[13]:     Traceback (most recent call last):
ehforwarderbot[13]:   File "/usr/lib/python3.7/site-packages/urllib3/connection.py", line 160, in _new_conn
ehforwarderbot[13]:     (self._dns_host, self.port), self.timeout, **extra_kw)
ehforwarderbot[13]:   File "/usr/lib/python3.7/site-packages/urllib3/util/connection.py", line 57, in create_connection
ehforwarderbot[13]:     for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
ehforwarderbot[13]:   File "/usr/lib/python3.7/socket.py", line 748, in getaddrinfo
ehforwarderbot[13]:     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
ehforwarderbot[13]: socket.gaierror: [Errno -3] Temporary failure in name resolution
ehforwarderbot[13]: During handling of the above exception, another exception occurred:
ehforwarderbot[13]: Traceback (most recent call last):
ehforwarderbot[13]:   File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 603, in urlopen
ehforwarderbot[13]:     chunked=chunked)
ehforwarderbot[13]:   File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 344, in _make_request
ehforwarderbot[13]:     self._validate_conn(conn)
ehforwarderbot[13]:   File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 843, in _validate_conn
ehforwarderbot[13]:     conn.connect()
ehforwarderbot[13]:   File "/usr/lib/python3.7/site-packages/urllib3/connection.py", line 305, in connect
ehforwarderbot[13]:     conn = self._new_conn()
ehforwarderbot[13]:   File "/usr/lib/python3.7/site-packages/urllib3/connection.py", line 169, in _new_conn
ehforwarderbot[13]:     self, "Failed to establish a new connection: %s" % e)
ehforwarderbot[13]: urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7f3c563f69e8>: Failed to establish a new connection: [Errno -3] Temporary failure in >
ehforwarderbot[13]: During handling of the above exception, another exception occurred:
ehforwarderbot[13]: Traceback (most recent call last):
ehforwarderbot[13]:   File "/usr/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
ehforwarderbot[13]:     timeout=timeout
ehforwarderbot[13]:   File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 641, in urlopen
ehforwarderbot[13]:     _stacktrace=sys.exc_info()[2])
ehforwarderbot[13]:   File "/usr/lib/python3.7/site-packages/urllib3/util/retry.py", line 399, in increment
ehforwarderbot[13]:     raise MaxRetryError(_pool, url, error or ResponseError(cause))
ehforwarderbot[13]: urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='login.weixin.qq.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.Ver>
ehforwarderbot[13]: During handling of the above exception, another exception occurred:
ehforwarderbot[13]: Traceback (most recent call last):
ehforwarderbot[13]:   File "/var/lib/efb/.local/lib/python3.7/site-packages/itchat/utils.py", line 125, in test_connect
ehforwarderbot[13]:     r = requests.get(config.BASE_URL)
ehforwarderbot[13]:   File "/usr/lib/python3.7/site-packages/requests/api.py", line 75, in get
ehforwarderbot[13]:     return request('get', url, params=params, **kwargs)
ehforwarderbot[13]:   File "/usr/lib/python3.7/site-packages/requests/api.py", line 60, in request
ehforwarderbot[13]:     return session.request(method=method, url=url, **kwargs)
ehforwarderbot[13]:   File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
ehforwarderbot[13]:     resp = self.send(prep, **send_kwargs)
ehforwarderbot[13]:   File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
ehforwarderbot[13]:     r = adapter.send(request, **kwargs)
ehforwarderbot[13]:   File "/usr/lib/python3.7/site-packages/requests/adapters.py", line 516, in send
ehforwarderbot[13]:     raise ConnectionError(e, request=request)
ehforwarderbot[13]: requests.exceptions.ConnectionError: HTTPSConnectionPool(host='login.weixin.qq.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.>
systemd[1]: efb@default.service: Succeeded.
```
 
</details>

**Comment by blueset** [comment]
`itchat` 在检测到连接失败时会强制 `sys.exit()`（退出状态为 0）。

https://github.com/littlecodersh/ItChat/blob/d5ce5db32ca15cef8eefa548a438a9fcc4502a6d/itchat/components/register.py#L22-L24

Blocked by #29.

**Comment by blueset** [comment]
已通过 #29 修复。
