### ISSUE TITLE
更新到最新版无法chat联系人或者link联系人

### ISSUE THREAD

**Issue by kettly1260** [blueset/efb-wechat-slave#56]
### 版本信息
EH Forwarder Bot
Version: 2.0.0b15
Python version:
3.6.5 (default, Apr  1 2018, 05:46:30) 
[GCC 7.3.0]

Master channel:
    Telegram Master (blueset.telegram) 2.0.0b22 # Default instance

Slave channel:
    WeChat Slave (blueset.wechat) <module 'efb_wechat_slave.__version__' from '/usr/local/lib/python3.6/dist-packages/efb_wechat_slave/__version__.py'> # Default instance

Middlewares:
    No middleware is enabled.

### 问题描述
chat和link命令都无法使用，一直显示在处理中

### 重现步骤

/link或者/chat可出现
卸载重装无效，退回到A18正常

### Verbose 日志
<details>
<summary>Verbose 日志</summary>

```
2019-06-03 09:23:36,041 [Level 99]: ehforwarderbot.main (main.init; main.py:96)
2019-06-03 09:23:50,087 [ERROR]: telegram.ext.dispatcher (dispatcher.process_update; dispatcher.py:301)
An uncaught error was raised while processing the update
Traceback (most recent call last):
File "/usr/local/lib/python3.6/dist-packages/telegram/ext/dispatcher.py", line 279, in process_update
handler.handle_update(update, self)
File "/usr/local/lib/python3.6/dist-packages/telegram/ext/commandhandler.py", line 173, in handle_update
return self.callback(dispatcher.bot, update, **optional_args)
File "/usr/local/lib/python3.6/dist-packages/efb_telegram_master/chat_binding.py", line 665, in start_chat_list
return self.chat_head_req_generate(bot, target, pattern=" ".join(args), chats=chats)
File "/usr/local/lib/python3.6/dist-packages/efb_telegram_master/chat_binding.py", line 714, in chat_head_req_generate
source_chats=chats)
File "/usr/local/lib/python3.6/dist-packages/efb_telegram_master/chat_binding.py", line 318, in slave_chats_pagination
slave_chats = slave.get_chats()
File "/usr/local/lib/python3.6/dist-packages/efb_wechat_slave/init.py", line 584, in get_chats
return self.chats.get_chats()
File "/usr/local/lib/python3.6/dist-packages/efb_wechat_slave/chats.py", line 109, in get_chats
l = [self.wxpy_chat_to_efb_chat(self.bot.file_helper)]
File "/usr/local/lib/python3.6/dist-packages/efb_wechat_slave/chats.py", line 103, in wxpy_chat_to_efb_chat
efb_chat.vendor_specific.update(self.generate_vendor_specific(chat))
File "/usr/local/lib/python3.6/dist-packages/efb_wechat_slave/chats.py", line 172, in generate_vendor_specific
contact_flag = raw['ContactFlag']
KeyError: 'ContactFlag'


```
 
</details>

**Comment by kettly1260** [comment]
2019-06-03 09:23:36,041 [Level 99]: ehforwarderbot.__main__ (__main__.init; __main__.py:96)
2019-06-03 09:23:50,087 [ERROR]: telegram.ext.dispatcher (dispatcher.process_update; dispatcher.py:301)
    An uncaught error was raised while processing the update
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/telegram/ext/dispatcher.py", line 279, in process_update
    handler.handle_update(update, self)
  File "/usr/local/lib/python3.6/dist-packages/telegram/ext/commandhandler.py", line 173, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "/usr/local/lib/python3.6/dist-packages/efb_telegram_master/chat_binding.py", line 665, in start_chat_list
    return self.chat_head_req_generate(bot, target, pattern=" ".join(args), chats=chats)
  File "/usr/local/lib/python3.6/dist-packages/efb_telegram_master/chat_binding.py", line 714, in chat_head_req_generate
    source_chats=chats)
  File "/usr/local/lib/python3.6/dist-packages/efb_telegram_master/chat_binding.py", line 318, in slave_chats_pagination
    slave_chats = slave.get_chats()
  File "/usr/local/lib/python3.6/dist-packages/efb_wechat_slave/__init__.py", line 584, in get_chats
    return self.chats.get_chats()
  File "/usr/local/lib/python3.6/dist-packages/efb_wechat_slave/chats.py", line 109, in get_chats
    l = [self.wxpy_chat_to_efb_chat(self.bot.file_helper)]
  File "/usr/local/lib/python3.6/dist-packages/efb_wechat_slave/chats.py", line 103, in wxpy_chat_to_efb_chat
    efb_chat.vendor_specific.update(self.generate_vendor_specific(chat))
  File "/usr/local/lib/python3.6/dist-packages/efb_wechat_slave/chats.py", line 172, in generate_vendor_specific
    contact_flag = raw['ContactFlag']
KeyError: 'ContactFlag'
2019-06-03 09:26:18,834 [ERROR]: telegram.ext.dispatcher (dispatcher.process_update; dispatcher.py:301)
    An uncaught error was raised while processing the update
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/telegram/ext/dispatcher.py", line 279, in process_update
    handler.handle_update(update, self)
  File "/usr/local/lib/python3.6/dist-packages/telegram/ext/commandhandler.py", line 173, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "/usr/local/lib/python3.6/dist-packages/efb_telegram_master/chat_binding.py", line 259, in link_chat_show_list
    return self.link_chat_gen_list(message.from_user.id, pattern=" ".join(args))
  File "/usr/local/lib/python3.6/dist-packages/efb_telegram_master/chat_binding.py", line 411, in link_chat_gen_list
    source_chats=chats)
  File "/usr/local/lib/python3.6/dist-packages/efb_telegram_master/chat_binding.py", line 318, in slave_chats_pagination
    slave_chats = slave.get_chats()
  File "/usr/local/lib/python3.6/dist-packages/efb_wechat_slave/__init__.py", line 584, in get_chats
    return self.chats.get_chats()
  File "/usr/local/lib/python3.6/dist-packages/efb_wechat_slave/chats.py", line 109, in get_chats
    l = [self.wxpy_chat_to_efb_chat(self.bot.file_helper)]
  File "/usr/local/lib/python3.6/dist-packages/efb_wechat_slave/chats.py", line 103, in wxpy_chat_to_efb_chat
    efb_chat.vendor_specific.update(self.generate_vendor_specific(chat))
  File "/usr/local/lib/python3.6/dist-packages/efb_wechat_slave/chats.py", line 172, in generate_vendor_specific
    contact_flag = raw['ContactFlag']
KeyError: 'ContactFlag'
2019-06-03 09:27:57,998 [ERROR]: telegram.ext.dispatcher (dispatcher.process_update; dispatcher.py:301)
    An uncaught error was raised while processing the update
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/telegram/ext/dispatcher.py", line 279, in process_update
    handler.handle_update(update, self)
  File "/usr/local/lib/python3.6/dist-packages/telegram/ext/commandhandler.py", line 173, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "/usr/local/lib/python3.6/dist-packages/efb_telegram_master/chat_binding.py", line 259, in link_chat_show_list
    return self.link_chat_gen_list(message.from_user.id, pattern=" ".join(args))
  File "/usr/local/lib/python3.6/dist-packages/efb_telegram_master/chat_binding.py", line 411, in link_chat_gen_list
    source_chats=chats)
  File "/usr/local/lib/python3.6/dist-packages/efb_telegram_master/chat_binding.py", line 318, in slave_chats_pagination
    slave_chats = slave.get_chats()
  File "/usr/local/lib/python3.6/dist-packages/efb_wechat_slave/__init__.py", line 584, in get_chats
    return self.chats.get_chats()
  File "/usr/local/lib/python3.6/dist-packages/efb_wechat_slave/chats.py", line 109, in get_chats
    l = [self.wxpy_chat_to_efb_chat(self.bot.file_helper)]
  File "/usr/local/lib/python3.6/dist-packages/efb_wechat_slave/chats.py", line 103, in wxpy_chat_to_efb_chat
    efb_chat.vendor_specific.update(self.generate_vendor_specific(chat))
  File "/usr/local/lib/python3.6/dist-packages/efb_wechat_slave/chats.py", line 172, in generate_vendor_specific
    contact_flag = raw['ContactFlag']
KeyError: 'ContactFlag'

**Comment by ChandelierX** [comment]
Yes I can reproduce the same issue on my machine with 
efb-telegram-master (2.0.0b22)
wechat-slave (2.0.0a20)

**Comment by concurrentz** [comment]
Same as my situation. Showed 'Key_error' / contact_flag missing.
Then i uninstall efb-wechat-slave (2.0.0a20). It became functional by Installing version 2.0.0a18

**Comment by leelaylay** [comment]
> Same as my situation. Showed 'Key_error' / contact_flag missing.
> Then i uninstall efb-wechat-slave (2.0.0a20). It became functional by Installing version 2.0.0a18

Thank you. I just do what you say and it works.

```shell
# uninstall 2.0.0a20 version 
pip3 uninstall efb-wechat-slave
# install 2.0.0a18 version 
pip3 install efb-wechat-slave==2.0.0a18
```

**Comment by JJ-Gui** [comment]
有個折中的方法，先在a18上/link 聯繫人到Group，再更新到a20....
a18無法發送表情還是麻煩了點。

**Comment by concurrentz** [comment]
You could send the stickers via middleware [EFB Sticker2Img](https://github.com/catbaron0/efb-sticker2img-middleware).
But the downside of this is gonna be that the stickers will be sent as photos in jpg

**Comment by kettly1260** [comment]
> You could send the stickers via middleware [EFB Sticker2Img](https://github.com/catbaron0/efb-sticker2img-middleware).
> But the downside of this is gonna be that the stickers will be sent as photos in jpg

@concurrentz 按照您给的这个中间件，安装之后出现了如下问题：

Traceback (most recent call last):
  File "/usr/local/bin/ehforwarderbot", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/ehforwarderbot/__main__.py", line 260, in main
    conf = config.load_config()
  File "/usr/local/lib/python3.6/dist-packages/ehforwarderbot/config.py", line 71, in load_config
    raise ValueError("\"%s\" is not found." % i)
ValueError: "catbaron.sticker2img" is not found.

**Comment by concurrentz** [comment]
> > You could send the stickers via middleware [EFB Sticker2Img](https://github.com/catbaron0/efb-sticker2img-middleware).
> > But the downside of this is gonna be that the stickers will be sent as photos in jpg
> 
> @concurrentz 按照您给的这个中间件，安装之后出现了如下问题：
> 
> Traceback (most recent call last):
> File "/usr/local/bin/ehforwarderbot", line 10, in 
> sys.exit(main())
> File "/usr/local/lib/python3.6/dist-packages/ehforwarderbot/**main**.py", line 260, in main
> conf = config.load_config()
> File "/usr/local/lib/python3.6/dist-packages/ehforwarderbot/config.py", line 71, in load_config
> raise ValueError(""%s" is not found." % i)
> ValueError: "catbaron.sticker2img" is not found.

Show me the screenshot of the `config.yaml` as well as  the location.
Beside, you need to restart `ehforwarderbot`, too.

**Comment by JJ-Gui** [comment]
> You could send the stickers via middleware [EFB Sticker2Img](https://github.com/catbaron0/efb-sticker2img-middleware).
> But the downside of this is gonna be that the stickers will be sent as photos in jpg

Thank You，It works

**Comment by kettly1260** [comment]
> > > You could send the stickers via middleware [EFB Sticker2Img](https://github.com/catbaron0/efb-sticker2img-middleware).
> > > But the downside of this is gonna be that the stickers will be sent as photos in jpg
> > 
> > 
> > @concurrentz 按照您给的这个中间件，安装之后出现了如下问题：
> > Traceback (most recent call last):
> > File "/usr/local/bin/ehforwarderbot", line 10, in
> > sys.exit(main())
> > File "/usr/local/lib/python3.6/dist-packages/ehforwarderbot/**main**.py", line 260, in main
> > conf = config.load_config()
> > File "/usr/local/lib/python3.6/dist-packages/ehforwarderbot/config.py", line 71, in load_config
> > raise ValueError(""%s" is not found." % i)
> > ValueError: "catbaron.sticker2img" is not found.
> 
> Show me the screenshot of the `config.yaml` as well as the location(relative path).
> Beside, you need to restart `ehforwarderbot`, too.

@concurrentz Hello, I know where the problem is.
Is this the content of the GIF library that cannot be sent,
 the bot prompts Message is not sent.
ValueError('bad transparency mask',)

**Comment by concurrentz** [comment]
> > > > You could send the stickers via middleware [EFB Sticker2Img](https://github.com/catbaron0/efb-sticker2img-middleware).
> > > > But the downside of this is gonna be that the stickers will be sent as photos in jpg
> > > 
> > > 
> > > @concurrentz 按照您给的这个中间件，安装之后出现了如下问题：
> > > Traceback (most recent call last):
> > > File "/usr/local/bin/ehforwarderbot", line 10, in
> > > sys.exit(main())
> > > File "/usr/local/lib/python3.6/dist-packages/ehforwarderbot/**main**.py", line 260, in main
> > > conf = config.load_config()
> > > File "/usr/local/lib/python3.6/dist-packages/ehforwarderbot/config.py", line 71, in load_config
> > > raise ValueError(""%s" is not found." % i)
> > > ValueError: "catbaron.sticker2img" is not found.
> > 
> > 
> > Show me the screenshot of the `config.yaml` as well as the location(relative path).
> > Beside, you need to restart `ehforwarderbot`, too.
> 
> @concurrentz Hello, I have solved it. But I met another problem.
> Is this the content of the GIF library that cannot be sent,
> the bot prompts Message is not sent.
> ValueError('bad transparency mask',)

Yes, it is. No substitute for sending gif now

**Comment by blueset** [comment]
感谢汇报这一问题，目前已于 3678e6d (alpha 22) 里面修复了这一问题。

**Comment by concurrentz** [comment]
Thanks, it works now.

**Comment by l-we** [comment]
> 感谢汇报，目前已于 [3678e6d](https://github.com/blueset/efb-wechat-slave/commit/3678e6d3cfc313941fdb3a60a5d3b2ce9a7b213a) (alpha 22) 里面修复了这一问题。

Webhook 依然无法chat联系人或者link联系人

**Comment by zsbai** [comment]
> > You could send the stickers via middleware [EFB Sticker2Img](https://github.com/catbaron0/efb-sticker2img-middleware).
> > But the downside of this is gonna be that the stickers will be sent as photos in jpg
> 
> @concurrentz 按照您给的这个中间件，安装之后出现了如下问题：
> 
> Traceback (most recent call last): File "/usr/local/bin/ehforwarderbot", line 10, in sys.exit(main()) File "/usr/local/lib/python3.6/dist-packages/ehforwarderbot/**main**.py", line 260, in main conf = config.load_config() File "/usr/local/lib/python3.6/dist-packages/ehforwarderbot/config.py", line 71, in load_config raise ValueError(""%s" is not found." % i) ValueError: "catbaron.sticker2img" is not found.

请教如何解决`ValueError: "catbaron.sticker2img" is not found`， 我也遇到了相同的问题
