### ISSUE TITLE
更新到a22之后经常出现不支持信息

### ISSUE THREAD

**Issue by kettly1260** [blueset/efb-wechat-slave#58]
### 版本信息
b22,a22 
EH Forwarder Bot
Version: 2.0.0b15
Python version:
3.6.4 (default, Jun 10 2019, 18:57:55) 
[GCC 6.3.0 20170516]

Master channel:
    Telegram Master (blueset.telegram) 2.0.0b22 # Default instance

Slave channel:
    WeChat Slave (blueset.wechat) <module 'efb_wechat_slave.__version__' from '/usr/local/lib/python3.6/site-packages/efb_wechat_slave/__version__.py'> # Default instance

Middlewares:
    No middleware is enabled.

### 问题描述
登录之后经常会不定时出现不支持信息

X, [12.06.19 20:11]
💬💻 微信团队: (不支持)
[Unsupported message, please check your phone.]

X, [12.06.19 21:33]
💬💻 微信团队: (不支持)
[Unsupported message, please check your phone.]

X, [12.06.19 22:56]
💬💻 微信团队: (不支持)
[Unsupported message, please check your phone.]

进入手机版查看又没有提醒，在 后台也看不到相关日志

### 重现步骤
登录就会不定时出现，近期发现可能是因为收到了由其他软件发的分享链接，就会同时出现一条不支持信息又会收到那条链接信息

### Verbose 日志
<details>
<summary>Verbose 日志</summary>

```
2530129; Reactions: {}; File: None (None @ None), None; Vendor: {}>
TimedOut()                                                                                        Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 402, in _make_request                                                                       six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/usr/local/lib/python3.6/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 398, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.6/http/client.py", line 1331, in getresponse                           response.begin()
  File "/usr/local/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()                                                   File "/usr/local/lib/python3.6/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.6/socket.py", line 586, in readinto                                    return self._sock.recv_into(b)
  File "/usr/local/lib/python3.6/ssl.py", line 1009, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/local/lib/python3.6/ssl.py", line 871, in read
    return self._sslobj.read(len, buffer)
  File "/usr/local/lib/python3.6/ssl.py", line 631, in read                                           v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out                                                      
During handling of the above exception, another exception occurred:                               
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/telegram/utils/request.py", line 203, in _request_wrapper
    resp = self._con_pool.request(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/telegram/vendor/ptb_urllib3/urllib3/request.py", line 70, in request
    **urlopen_kw)
  File "/usr/local/lib/python3.6/site-packages/telegram/vendor/ptb_urllib3/urllib3/request.py", line 148, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/usr/local/lib/python3.6/site-packages/telegram/vendor/ptb_urllib3/urllib3/poolmanager.py", line 244, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/local/lib/python3.6/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 666, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.6/site-packages/telegram/vendor/ptb_urllib3/urllib3/util/retry.py", line 347, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.6/site-packages/telegram/vendor/ptb_urllib3/urllib3/packages/six.py", line 686, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 617, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.6/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 405, in _make_request
    exc_cls=ReadTimeoutError)
  File "/usr/local/lib/python3.6/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 321, in _raise_timeout
    raise exc_cls(*args)
telegram.vendor.ptb_urllib3.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=15)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/efb_telegram_master/slave_message.py", line 136, in send_message
    tg_msg = self.slave_message_text(msg, tg_dest, msg_template, old_msg_id, target_msg_id, reply_markup)
  File "/usr/local/lib/python3.6/site-packages/efb_telegram_master/slave_message.py", line 235, in slave_message_text
    self.bot.send_chat_action(tg_dest, telegram.ChatAction.TYPING)
  File "/usr/local/lib/python3.6/site-packages/efb_telegram_master/bot_manager.py", line 364, in send_chat_action
    return self.updater.bot.send_chat_action(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/telegram/bot.py", line 65, in decorator
    result = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/telegram/bot.py", line 1378, in send_chat_action
    result = self._request.post(url, data, timeout=timeout)
  File "/usr/local/lib/python3.6/site-packages/telegram/utils/request.py", line 309, in post
    headers={'Content-Type': 'application/json'})
  File "/usr/local/lib/python3.6/site-packages/telegram/utils/request.py", line 205, in _request_wrapper
    raise TimedOut()
telegram.error.TimedOut: Timed out



```
 
</details>

**Comment by blueset** [comment]
已知问题。将在下一版本解决。
