### ISSUE TITLE
Web WeChat logged your account out before master channel is ready

### ISSUE THREAD

**Issue by 404neko** [blueset/efb-wechat-slave#61]
### 版本信息
EH Forwarder Bot
Version: 2.0.0b15
Python version:
3.7.3 (default, Jul 20 2019, 13:01:31) 
[GCC 5.4.0 20160609]

Master channel:
    Telegram Master (blueset.telegram) 2.0.0b22 # Default instance

Slave channel:
    WeChat Slave (blueset.wechat) <module 'efb_wechat_slave.__version__' from '/usr/local/lib/python3.7/site-packages/efb_wechat_slave/__version__.py'> # Default instance

Middlewares:
    No middleware is enabled.

### 问题描述
无法使用efb-wechat 登录
但是同一主机使用itwechat 再命令行扫描可以登录

### 重现步骤
登录

### Verbose 日志
<details>
<summary>Verbose 日志</summary>

```
 ehforwarderbot
2019-07-20 13:47:02,795 [Level 99]: ehforwarderbot.__main__ (__main__.init; __main__.py:85)
     Initializing slave blueset.wechat... 
2019-07-20 13:47:05,370 [Level 99]: plugins.blueset.wechat.WeChatChannel (__init__.console_qr_code; __init__.py:206)
    Confirm on your phone.
2019-07-20 13:47:08,065 [Level 99]: plugins.blueset.wechat.WeChatChannel (__init__.console_qr_code; __init__.py:209)
    Successfully logged in.
2019-07-20 13:47:08,358 [Level 99]: ehforwarderbot.__main__ (__main__.init; __main__.py:96)
     Slave channel WeChat Slave (blueset.wechat) # Default profile is initialized. 
2019-07-20 13:47:08,358 [Level 99]: ehforwarderbot.__main__ (__main__.init; __main__.py:99)
     Initializing master blueset.telegram... 
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/site-packages/itchat/components/login.py", line 281, in maintain_loop
    exitCallback()
  File "/usr/local/lib/python3.7/site-packages/efb_wechat_slave/__init__.py", line 266, in exit_callback
    raise Exception(self._("Web WeChat logged your account out before master channel is ready."))
Exception: Web WeChat logged your account out before master channel is ready.

2019-07-20 13:47:09,593 [Level 99]: ehforwarderbot.__main__ (__main__.init; __main__.py:109)
     Master channel Telegram Master (blueset.telegram) # Default profile is initialized. 
2019-07-20 13:47:09,593 [Level 99]: ehforwarderbot.__main__ (__main__.init; __main__.py:111)
     All channels initialized. 
2019-07-20 13:47:09,593 [Level 99]: ehforwarderbot.__main__ (__main__.init; __main__.py:125)
     All middlewares are initialized. 
```

</details>

**Comment by blueset** [comment]
”Web WeChat logged your account out before master channel is ready.”  
「网页版微信在主端就绪前已将您登出。」

请尝试将您的登陆 Session 清除后重新登录。Session 文件存储在 `EFB_DATA_PATH/profiles/<YOUR_PROFILE>/blueset.wechat/wxpy.pkl`.

**Comment by 404neko** [comment]
已解决 谢谢
