### ISSUE TITLE
 an error occurred in <bound method SlaveMessageManager.Decorators.wechat_msg_meta.<locals>.thread_wrapper of <efb_wechat_slave.slave_message.SlaveMessageManager object at 0x7f97d02711d0>>.

### ISSUE THREAD

**Issue by l-we** [blueset/efb-wechat-slave#62]
```
2019-07-26 09:34:42,366 [Level 99]: ehforwarderbot.__main__ (__main__.init; __main__.py:85)
     Initializing slave blueset.wechat...
2019-07-26 09:34:45,659 [Level 99]: ehforwarderbot.__main__ (__main__.init; __main__.py:96)
     Slave channel WeChat Slave (blueset.wechat) # Default profile is initialized.
2019-07-26 09:34:45,659 [Level 99]: ehforwarderbot.__main__ (__main__.init; __main__.py:99)
     Initializing master blueset.telegram...
2019-07-26 09:34:47,003 [ERROR]: efb_wechat_slave.wxpy.api.bot (bot.process; bot.py:459)
    an error occurred in <bound method SlaveMessageManager.Decorators.wechat_msg_meta.<locals>.thread_wrapper of <efb_wechat_slave.slave_message.SlaveMessageManager object at 0x7f97d02711d0>>.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/efb_wechat_slave/wxpy/api/bot.py", line 455, in process
    ret = config.func(msg)
  File "/usr/local/lib/python3.7/dist-packages/efb_wechat_slave/slave_message.py", line 78, in thread_wrapper
    threading.Thread(target=wrap_func, args=args, kwargs=kwargs).run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/dist-packages/efb_wechat_slave/slave_message.py", line 70, in wrap_func
    efb_msg.deliver_to = coordinator.master
AttributeError: module 'ehforwarderbot.coordinator' has no attribute 'master'
2019-07-26 09:34:53,575 [Level 99]: ehforwarderbot.__main__ (__main__.init; __main__.py:109)
     Master channel Telegram Master (blueset.telegram) # Default profile is initialized.
2019-07-26 09:34:53,575 [Level 99]: ehforwarderbot.__main__ (__main__.init; __main__.py:111)
     All channels initialized.
2019-07-26 09:34:53,575 [Level 99]: ehforwarderbot.__main__ (__main__.init; __main__.py:125)
     All middlewares are initialized.
```

**Comment by blueset** [comment]
Please provide full detail on which version of framework and all modules enabled you are using.

**Comment by l-we** [comment]
该 EFB Telegram 主端版本为 2.0.0b22。检测到 1 个启用中的从端:
- 💬 WeChat Slave (blueset.wechat, 2.0.0a22)

**Comment by l-we** [comment]
admins 配置一个账号正常，配置2个的时候出现的问题，其中一个为bot

**Comment by blueset** [comment]
[ETM]: Telegram Bot API 不允许一个 bot 接收另一个 bot 的消息。

**Comment by l-we** [comment]
哦 想用bot给发微信消息呢，看来没办法实现了，
