### ISSUE TITLE
更新后报错.版本号不一致

### ISSUE THREAD

**Issue by shzxm** [blueset/efb-wechat-slave#65]
Traceback (most recent call last):
  File "/usr/local/bin/ehforwarderbot", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/ehforwarderbot/__main__.py", line 262, in main
    conf = config.load_config()
  File "/usr/local/lib/python3.6/dist-packages/ehforwarderbot/config.py", line 68, in load_config
    channel = utils.locate_module(i, 'slave')
  File "/usr/local/lib/python3.6/dist-packages/ehforwarderbot/utils.py", line 138, in locate_module
    return i.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2323, in load
    self.require(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2346, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 783, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (requests 2.18.4 (/usr/lib/python3/dist-packages), Requirement.parse('requests>=2.22.0'))

### 版本信息
2019年08月19日 最新版本

### 重现步骤
全新部署完之后报错

### Verbose 日志
<details>
<summary>Verbose 日志</summary>

```
请在这里贴出您的 Verbose 日志。如果您对隐私有所顾虑，您可以自行
隐去隐私信息、或 GPG 加密至 BD6B65EC00638DC9083781D5D4B65BB1A106200A。



```
 
</details>

**Comment by blueset** [comment]
请检查你所安装的其他 Python 软件包的冲突情况。如有必要，请使用 venv 安装。
