### ISSUE TITLE
无法大于1M的文件，返回连接超时

### ISSUE THREAD

**Issue by zhjnerv** [blueset/efb-wechat-slave#69]
### 版本信息

EH Forwarder Bot
Version: 2.0.0b19
Python version:
3.6.8 (default, May  2 2019, 20:40:44) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
Running on profile "default".

Master channel:
    Telegram Master (blueset.telegram) 2.0.0b25 # Default instance

Slave channel:
    WeChat Slave (blueset.wechat) 2.0.0a28 # Default instance

Middleware:
    Message Blocker Middleware (catbaron.msg_blocker) 0.0.1 # Default instance

### 问题描述

发送文件，大于1M返回：
` Message is not sent.

ConnectionError(ProtocolError('Connection aborted.', timeout('The write operation timed out',)),) `

### 重现步骤

已经在配置文件中启用了如下参数

request_kwargs:
    read_timeout: 300
    connect_timeout: 300

### Verbose 日志
<details>
<summary>Verbose 日志</summary>

```
File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 355, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib64/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1065, in _send_output
    self.send(chunk)
  File "/usr/lib64/python3.6/http/client.py", line 986, in send
    self.sock.sendall(data)
  File "/usr/lib64/python3.6/ssl.py", line 975, in sendall
    v = self.send(byte_view[count:])
  File "/usr/lib64/python3.6/ssl.py", line 944, in send
    return self._sslobj.write(data)
  File "/usr/lib64/python3.6/ssl.py", line 642, in write
    return self._sslobj.write(data)
socket.timeout: The write operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 641, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3.6/site-packages/urllib3/util/retry.py", line 368, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 603, in urlopen
    chunked=chunked)
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 355, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib64/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1065, in _send_output
    self.send(chunk)
  File "/usr/lib64/python3.6/http/client.py", line 986, in send
    self.sock.sendall(data)
  File "/usr/lib64/python3.6/ssl.py", line 975, in sendall
    v = self.send(byte_view[count:])
  File "/usr/lib64/python3.6/ssl.py", line 944, in send
    return self._sslobj.write(data)
  File "/usr/lib64/python3.6/ssl.py", line 642, in write
    return self._sslobj.write(data)
urllib3.exceptions.ProtocolError: ('Connection aborted.', timeout('The write operation timed out',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/efb_telegram_master/master_message.py", line 374, in process_telegram_message
    slave_msg = coordinator.send_message(m)
  File "/usr/lib/python3.6/site-packages/ehforwarderbot/coordinator.py", line 116, in send_message
    return slaves[msg.deliver_to.channel_id].send_message(msg)
  File "/usr/lib/python3.6/site-packages/efb_wechat_slave/__init__.py", line 400, in send_message
    r = self._bot_send_file(chat, msg.filename, file=msg.file)
  File "/usr/lib/python3.6/site-packages/efb_wechat_slave/__init__.py", line 598, in _bot_send_file
    return chat.send_file(filename, file=file)
urllib3.exceptions.ProtocolError: ('Connection aborted.', timeout('The write operation timed out',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/efb_telegram_master/master_message.py", line 374, in process_telegram_message
    slave_msg = coordinator.send_message(m)
  File "/usr/lib/python3.6/site-packages/ehforwarderbot/coordinator.py", line 116, in send_message
    return slaves[msg.deliver_to.channel_id].send_message(msg)
  File "/usr/lib/python3.6/site-packages/efb_wechat_slave/__init__.py", line 400, in send_message
    r = self._bot_send_file(chat, msg.filename, file=msg.file)
  File "/usr/lib/python3.6/site-packages/efb_wechat_slave/__init__.py", line 598, in _bot_send_file
    return chat.send_file(filename, file=file)
  File "/usr/lib/python3.6/site-packages/efb_wechat_slave/vendor/wxpy/api/chats/chat.py", line 54, in wrapped
    ret = do_send()
  File "/usr/lib/python3.6/site-packages/efb_wechat_slave/vendor/wxpy/utils/misc.py", line 67, in wrapped
    ret = func(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/efb_wechat_slave/vendor/wxpy/api/chats/chat.py", line 52, in do_send
    return itchat_partial_func(**itchat_call_or_ret)
  File "/usr/lib/python3.6/site-packages/efb_wechat_slave/vendor/itchat/components/messages.py", line 399, in send_file
    r = self.upload_file(fileDir, preparedFile=preparedFile)
  File "/usr/lib/python3.6/site-packages/efb_wechat_slave/vendor/itchat/components/messages.py", line 348, in upload_file
    file_, chunk, chunks, uploadMediaRequest)
  File "/usr/lib/python3.6/site-packages/efb_wechat_slave/vendor/itchat/components/messages.py", line 382, in upload_chunk_file
    return core.s.post(url, files=files, headers=headers, timeout=config.TIMEOUT)
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 581, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3.6/site-packages/efb_wechat_slave/vendor/wxpy/utils/misc.py", line 351, in customized_request
    return requests.Session.request(session, method, url, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', timeout('The write operation timed out',))
2019-09-18 15:09:35,057 [DEBUG]: peewee (peewee.execute_sql; peewee.py:2969)
    ('INSERT INTO "msglog" ("master_msg_id", "master_msg_id_alt", "slave_message_id", "text", "slave_origin_uid", "slave_origin_display_name", "slave_member_uid", "slave_member_display_name", "media_type", "mime", "file_id", "msg_type", "pickle", "sent_to", "time") VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)', ['198608165.64412', None, '__fail__.1568790575', 'Sent a MsgType.File', 'blueset.wechat filehelper', '__chat__', None, None, 'Document', 'application/zip', 'BQADBQADMAEAAngdEVTaLHe7FSZz3hYE', 'MsgType.File', <memory at 0x7fbee0388048>, 'slave', datetime.datetime(2019, 9, 18, 15, 9, 35, 56830)])
^CException ignored in: <module 'threading' from '/usr/lib64/python3.6/threading.py'>
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 1294, in _shutdown
    t.join()
  File "/usr/lib64/python3.6/threading.py", line 1056, in join
    self._wait_for_tstate_lock()
  File "/usr/lib64/python3.6/threading.py", line 1072, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):




```
 
</details>

**Comment by blueset** [comment]
这个超时事件出现在 EWS 方面，调整 ETM 的超时条件参数不会改变 EWS 的行为。请尝试转移到一个更佳的网络环境中重试。

**Comment by kettly1260** [comment]
> 这个超时事件出现在 EWS 方面，调整 ETM 的超时条件参数不会改变 EWS 的行为。请尝试转移到一个更佳的网络环境中重试。

请问怎么解决这个问题呢？以前是可以发送的，现在经常连GIF图片都发不出去
