### ISSUE TITLE
当前登录环境异常。为了你的帐号安全，暂时不能登录web微信。你可以通过手机客户端或者windows微信登录。

### ISSUE THREAD

**Issue by blueset** [blueset/efb-wechat-slave#7]
_From @watsy0007 on August 17, 2017 7:1_

```
2017-08-17 07:00:02,784: itchat [ERROR]
    Your wechat account may be LIMITED to log in WEB wechat, error info:
<error><ret>1203</ret><message>当前登录环境异常。为了你的帐号安全，暂时不能登录web微信。你可以通过手机客户端或者windows微信登录。</message></error>
```

_Copied from original issue: blueset/ehForwarderBot#74_

**Comment by blueset** [comment]
_From @watsy0007 on August 17, 2017 7:2_

@blueset

**Comment by blueset** [comment]
请参照[本篇 Wiki](https://github.com/blueset/ehForwarderBot/wiki/EWS:-Current-reports-regarding-potential-actions-that-triggers-Web-WeChat-ban)。

**Comment by zhoudavinci** [comment]
Linux操作系统下，Chromium的隐身模式下(Ctrl+Shift+N)可以正常打开，所以我觉得web端登录还检测了设备信息。

**Comment by blueset** [comment]
新的解封情况
- 禅（[支持群组，2019 年 12 月]）：封禁一天。期间尝试[申诉]，但未得到回复。

[申诉]: https://help.wechat.com/cgi-bin/newreadtemplate?t=help_center/w_feedback_form&lang=en&plat=android&Channel=
[支持群组，2019 年 12 月]: https://t.me/c/1083959736/62275

**Comment by blueset** [comment]
新的解封情况：
> 手机上 全局代理 当前要登录 vps 所在地的 代理
> 正常使用10分钟wechat
> 可解除 异常状态
>
> — shzxm, #106

**Comment by blueset** [comment]
新的解封情况

> emmm，最近那个linux wechat，好像能用来解封网页封号
> 方法是，就那上面登录一下就好了
> — [Eric Little](https://t.me/c/1083959736/77020), EFB Support Group

> 在统信 UOS 系统中安装微信(linux)版本，登录后，就可以登录网页微信
> — [TwentyNine](https://www.v2ex.com/t/740217), V2EX

**Comment by shzxm** [comment]
确认可以解封 先上图 再说过程

这个号是 无法登录web版wechat的
![image](https://user-images.githubusercontent.com/9905297/103339716-1bc37200-4abd-11eb-86ca-f08c5a0a0e72.png)

这个是登录了微信linux版
![image](https://user-images.githubusercontent.com/9905297/103339753-35fd5000-4abd-11eb-9ebd-94ebd03c6600.png)

这个是再次登录web版wechat的
![image](https://user-images.githubusercontent.com/9905297/103339773-41e91200-4abd-11eb-8654-6f989bc0d124.png)


确认 uos专业版 uos专业版 uos专业版 uos专业版 uos专业版 uos专业版 可以解封

uos专业版 可以安装 微信linux 

uos个人版 uos个人版 uos个人版 uos个人版 uos个人版 uos个人版 只能装微信wine

微信wine无法解封!!!微信wine无法解封!!!微信wine无法解封!!!

**Comment by shzxm** [comment]
2020-12-30 22:00:00 方法失效

> 确认可以解封先上图再说过程
> 
> 这个号是无法登录web版wechat的
> ![图片](https://user-images.githubusercontent.com/9905297/103339716-1bc37200-4abd-11eb-86ca-f08c5a0a0e72.png)
> 
> 这个是登录了微信linux版
> ![图片](https://user-images.githubusercontent.com/9905297/103339753-35fd5000-4abd-11eb-9ebd-94ebd03c6600.png)
> 
> 这个是再次登录web版wechat的
> ![图片](https://user-images.githubusercontent.com/9905297/103339773-41e91200-4abd-11eb-8654-6f989bc0d124.png)
> 
> 确认uos专业版uos专业版uos专业版uos专业版uos专业版uos专业版可以解封
> 
> uos专业版可以安装微信linux
> 
> uos个人版uos个人版uos个人版uos个人版uos个人版uos个人版只能装微信wine
> 
> 微信酒无法解封!!!微信酒无法解封!!!

**Comment by markwhitey** [comment]
> 2020-12-30 22:00:00 方法失效
> 
> > 确认可以解封先上图再说过程
> > 这个号是无法登录web版wechat的
> > ![图片](https://user-images.githubusercontent.com/9905297/103339716-1bc37200-4abd-11eb-86ca-f08c5a0a0e72.png)
> > 这个是登录了微信linux版
> > ![图片](https://user-images.githubusercontent.com/9905297/103339753-35fd5000-4abd-11eb-9ebd-94ebd03c6600.png)
> > 这个是再次登录web版wechat的
> > ![图片](https://user-images.githubusercontent.com/9905297/103339773-41e91200-4abd-11eb-8654-6f989bc0d124.png)
> > 确认uos专业版可以解封
> > uos专业版可以安装微信linux
> > uos个人版只能装微信wine
> > 微信wine无法解封!

这么快就失效了吗

**Comment by shzxm** [comment]
> > 2020-12-30 22:00:00方法失效
> > > 确认可以解封先上图再说过程
> > > 这个号是无法登录网络版
> > > 微信的这个是登录了微信linux版
> > > 这个是再次登录网络版微信的
> > > 确认uos专业版可以解封
> > > uos专业版可以安装微信linux 
> > > uos个人版只能装微信wine
> > > 微信wine无法解封！
> > > ![图片](https://user-images.githubusercontent.com/9905297/103339716-1bc37200-4abd-11eb-86ca-f08c5a0a0e72.png)
> > > ![图片](https://user-images.githubusercontent.com/9905297/103339753-35fd5000-4abd-11eb-9ebd-94ebd03c6600.png)
> > > ![图片](https://user-images.githubusercontent.com/9905297/103339773-41e91200-4abd-11eb-8654-6f989bc0d124.png)
> 
> 这么快就不一定了吗

是的呢.不过说不定还会有

**Comment by xja** [comment]
去年我的账号能登陆网页版，今年就不行了，但是用QQ浏览器的微信插件又能顺利登陆，微信可真的是太厉害了

**Comment by blueset** [comment]
再续，发现了一个有意思的 Chrome 扩展。
说不定可以试试。

https://github.com/adamyi/wechrome

**Comment by terrytw** [comment]
有几篇文章提到itchat的header只有ua，可能是很明显的特征
https://blog.csdn.net/codingpy/article/details/107075492
https://www.cola666.top/blog/detail/16#wow3

**Comment by artxia** [comment]
> 再续，发现了一个有意思的 Chrome 扩展。
> 说不定可以试试。
> 
> https://github.com/adamyi/wechrome

这位大佬使用 UOS 绕过 web 微信登录限制，修复了 ItChat 登录
希望EFB能跟进
https://github.com/luvletter2333/ItChat
https://github.com/luvletter2333/ItChat/commit/9c49b4a5c36842003a48097694bcb3bd13f6e96d

**Comment by blueset** [comment]
@artxia 
感谢提醒，已将补丁应用到 EWS 的 itchat 里面。（8312b767）
已推送到 GitHub，待发布到 PyPI。

**Comment by terrytw** [comment]
请问作者有修改header的计划吗

**Comment by artxia** [comment]
> @artxia
> 感谢提醒，已将补丁应用到 EWS 的 itchat 里面。（ [8312b76](https://github.com/ehForwarderBot/efb-wechat-slave/commit/8312b767f47328f8da3a83817c51e59190815322) ）
> 已推送到 GitHub，待发布到 PyPI。

本地安装测试，以前不能使用的微信号已经可以成功登录！

**Comment by blueset** [comment]
> @terrytw 
> 请问作者有修改header的计划吗

目前还不太清楚缺少 header 是不是和 wc 封号直接相关，而且现在添加了 UOS 头补丁之后也不太确定 UOS 客户端的请求还带了什么其他字段。

不过在配置文件里面增加一个自定义 header 估计应该可以（但是这个设置应该不会进 EWS 的配置向导，这种数据结构交互做起来太麻烦了）

**Comment by shzxm** [comment]
所以现在uos又可以复活了？那…火速转发

**Comment by daisyxu917** [comment]
实测：两个微信号，一个后申请的可以登陆。先申请的依旧无法登陆，但不返回“无法登陆网页微信”的错误，而是停在confirm on phone。这个号之前因为用第三方插件被封过，不清楚是不是这个原因无法登陆。

供参考

**Comment by soul-cat** [comment]
我号13年左右注册，没登过web版微信，听说的时候已经完全登不上了。
现在通过 https://github.com/adamyi/wechrome 这个插件登录回显  <error><ret>1203</ret><message>当前微信版本过低，请升级至最新版本。</message></error>

**Comment by daisyxu917** [comment]
今天好似又失效了？提示message is not sent 但是手机端依旧显示桌面微信登陆中

**Comment by cjh0613** [comment]
占楼

**Comment by cjh0613** [comment]
微信号不能网页登陆。

看到有发布补丁，使用`git clone`最新代码源码安装，扫码后还是会报错`KeyError: 'wxsid'`。详见下方。

是还需配置其他依赖吗？或还有其他可以尝试登陆的方法吗？



### 版本信息 Version Info


```
EH Forwarder Bot
版本: 2.1.0
Python 版本:
3.6.8 (default, Nov 16 2020, 16:55:22) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]
正在使用配置文件「default」。

主端:
    Telegram Master (blueset.telegram) 2.2.3 # 默认实例

从端:
    WeChat Slave (blueset.wechat) 2.0.5.dev4 # 默认实例

中间件:
    尚未启用任何中间件。
```

### 问题描述 Describe the bug

扫码后报错`KeyError: 'wxsid'`，详见日志

### 重现步骤 To Reproduce

```
编辑  ~/.ehforwarderbot/profiles/default/config.yaml 为

master_channel: blueset.telegram
slave_channels:
- blueset.wechat

编辑  ~/.ehforwarderbot/profiles/default/blueset.telegram/config.yaml 为

token: "9999998888:AAEUZDtBEiDKykuI0VroA8WCOkjtsW4wPsI"
admins: [6666666666]

运行：

screen -S wechat

ehforwarderbot
```

### Verbose 日志 Log
<details>
<summary>Verbose 日志</summary>

```
请在下方贴出您的 Verbose 日志。如果您对隐私有所顾虑，您可以自行
隐去隐私信息、或 GPG 加密至 BD6B65EC00638DC9083781D5D4B65BB1A106200A。

【贴在下面】

2021-04-15 22:02:35,626 [DEBUG]: itchat (hotreload.dump_login_status; hotreload.py:35)
    Attempting to overwrite session file.
2021-04-15 22:02:35,626 [DEBUG]: itchat (hotreload.dump_login_status; hotreload.py:37)
    Write session file to /root/.ehforwarderbot/profiles/default/blueset.wechat/wxpy.pkl.4KMuw7qhabs.
2021-04-15 22:02:35,626 [DEBUG]: itchat (hotreload.dump_login_status; hotreload.py:40)
    Remove old session file at /root/.ehforwarderbot/profiles/default/blueset.wechat/wxpy.pkl
2021-04-15 22:02:35,626 [DEBUG]: itchat (hotreload.dump_login_status; hotreload.py:42)
    Move new session file from /root/.ehforwarderbot/profiles/default/blueset.wechat/wxpy.pkl.4KMuw7qhabs to /root/.ehforwarderbot/profiles/default/blueset.wechat/wxpy.pkl
2021-04-15 22:02:35,626 [DEBUG]: itchat (hotreload.dump_login_status; hotreload.py:44)
    Session file overwrite completed.
2021-04-15 22:02:35,626 [DEBUG]: itchat (hotreload.dump_login_status; hotreload.py:46)
    Dump login status for hot reload successfully.
Traceback (most recent call last):
  File "/usr/local/bin/ehforwarderbot", line 33, in <module>
    sys.exit(load_entry_point('ehforwarderbot==2.1.0', 'console_scripts', 'ehforwarderbot')())
  File "/usr/local/lib/python3.6/site-packages/ehforwarderbot/__main__.py", line 339, in main
    init(conf)
  File "/usr/local/lib/python3.6/site-packages/ehforwarderbot/__main__.py", line 135, in init
    coordinator.add_channel(cls(instance_id=instance_id))
  File "/usr/local/lib/python3.6/site-packages/efb_wechat_slave-2.0.5.dev4-py3.6.egg/efb_wechat_slave/__init__.py", line 157, in __init__
    self.authenticate('console_qr_code', first_start=True)
  File "/usr/local/lib/python3.6/site-packages/efb_wechat_slave-2.0.5.dev4-py3.6.egg/efb_wechat_slave/__init__.py", line 666, in authenticate
    start_immediately=not first_start)
  File "/usr/local/lib/python3.6/site-packages/efb_wechat_slave-2.0.5.dev4-py3.6.egg/efb_wechat_slave/vendor/wxpy/api/bot.py", line 98, in __init__
    enhance_webwx_request(self)
  File "/usr/local/lib/python3.6/site-packages/efb_wechat_slave-2.0.5.dev4-py3.6.egg/efb_wechat_slave/vendor/wxpy/utils/misc.py", line 326, in enhance_webwx_request
    '&pass_ticket={li[pass_ticket]}'.format(li=login_info)
KeyError: 'wxsid'
2021-04-15 22:02:35,628 [INFO]: ehforwarderbot.__main__ (__main__.stop_gracefully; __main__.py:103)
    Valid master channel is not found.

【贴在上面】

```
 
</details>

**Comment by shzxm** [comment]
> 微信号不能网页登陆。
> 
> 看到有发布补丁，使用最新代码源码安装，扫码后还是会报错。详见下方。`git clone``KeyError: 'wxsid'`
> 
> 是还需配置其他依赖吗？或还有其他可以尝试登陆的方法吗？
> 
> ### 图文并下版本信息
> ```
> EH Forwarder Bot
> 版本: 2.1.0
> Python 版本:
> 3.6.8 (default, Nov 16 2020, 16:55:22) 
> [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]
> 正在使用配置文件「default」。
> 
> 主端:
>     Telegram Master (blueset.telegram) 2.2.3 # 默认实例
> 
> 从端:
>     WeChat Slave (blueset.wechat) 2.0.5.dev4 # 默认实例
> 
> 中间件:
>     尚未启用任何中间件。
> ```
> 
> ### 问题描述错误
> 扫码后报错，详见日志`KeyError: 'wxsid'`
> 
> ### 重现的次要
> ```
> 编辑  ~/.ehforwarderbot/profiles/default/config.yaml 为
> 
> master_channel: blueset.telegram
> slave_channels:
> - blueset.wechat
> 
> 编辑  ~/.ehforwarderbot/profiles/default/blueset.telegram/config.yaml 为
> 
> token: "9999998888:AAEUZDtBEiDKykuI0VroA8WCOkjtsW4wPsI"
> admins: [6666666666]
> 
> 运行：
> 
> screen -S wechat
> 
> ehforwarderbot
> ```
> 
> ### 冗长的日志
> 韦尔博斯·斯马德

登陆下网页端先看看是什么，再说其他的，wxdis 可能是异地登陆

**Comment by cjh0613** [comment]
@shzxm 

确实是异地登录，服务器在海外。

那么我接下来是本地网页登陆试试；还是手机代理后尝试登陆？同一地区 ip 不同算异地登陆吗（不是用此服务器作代理）？

**Comment by shzxm** [comment]
> @shzxm
> 
> 确实是异地登录，服务器在海外。
> 
> 那么我接下来是本地网页登陆试试；还是手机代理后尝试登陆？同一地区 ip 不同算异地登陆吗（不是用此服务器作代理）？

全局挂你要使用的服务器代理，先登录下web，然后再试

**Comment by phoenixxie7** [comment]
> > 微信号不能网页登陆。
> > 看到有发布补丁，使用最新代码源码安装，扫码后还是会报错。详见下方。`` git clone``KeyError: 'wxsid' ``
> > 是还需配置其他依赖吗？或还有其他可以尝试登陆的方法吗？
> > ### 图文并下版本信息
> > ```
> > EH Forwarder Bot
> > 版本: 2.1.0
> > Python 版本:
> > 3.6.8 (default, Nov 16 2020, 16:55:22) 
> > [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]
> > 正在使用配置文件「default」。
> > 
> > 主端:
> >     Telegram Master (blueset.telegram) 2.2.3 # 默认实例
> > 
> > 从端:
> >     WeChat Slave (blueset.wechat) 2.0.5.dev4 # 默认实例
> > 
> > 中间件:
> >     尚未启用任何中间件。
> > ```
> > 
> > 
> > ### 问题描述错误
> > 扫码后报错，详见日志`KeyError: 'wxsid'`
> > ### 重现的次要
> > ```
> > 编辑  ~/.ehforwarderbot/profiles/default/config.yaml 为
> > 
> > master_channel: blueset.telegram
> > slave_channels:
> > - blueset.wechat
> > 
> > 编辑  ~/.ehforwarderbot/profiles/default/blueset.telegram/config.yaml 为
> > 
> > token: "9999998888:AAEUZDtBEiDKykuI0VroA8WCOkjtsW4wPsI"
> > admins: [6666666666]
> > 
> > 运行：
> > 
> > screen -S wechat
> > 
> > ehforwarderbot
> > ```
> > 
> > 
> > ### 冗长的日志
> > 韦尔博斯·斯马德
> 
> 登陆下网页端先看看是什么，再说其他的，wxsid 可能是异地登陆

同问题出现KeyError: 'wxsid'。但是用的是本地linux虚拟机，应该不存在异地登录问题。

**Comment by gitiray** [comment]
> 
> 
> 再续，发现了一个有意思的 Chrome 扩展。 说不定可以试试。
> 
> https://github.com/adamyi/wechrome

很厉害，我的微信帐号一年多无法登录web了，装这个插件直接原地复活

**Comment by ccbentlee** [comment]
> > 再续，发现了一个有意思的 Chrome 扩展。 说不定可以试试。
> > https://github.com/adamyi/wechrome
> 
> 很厉害，我的微信帐号一年多无法登录web了，装这个插件直接原地复活

ehbot现在能用么？Tel聊微信那个。

**Comment by blueset** [comment]
新发现的可解封 Web WC 的方法（仅适用于部分用户）

> 先用新上线的网页版文件传输助手 https://filehelper.weixin.qq.com/ 随便传个文件
> 再去登录 https://wx.qq.com/ 就会发现微信网页版可以正常登录了

经测试，并不是所有用户都能以此方法解封。

消息来源：
* https://hostloc.com/thread-946732-1-2.html
* https://t.me/PufferOverflow/1618
* https://t.me/c/1083959736/84729

**Comment by gaxdel** [comment]
今天登出之后，再重新登录，网页版又无法登录了。。。

**Comment by wrhsd1** [comment]
我的是网页文件助手复活的，31号下线了，在本地网页版可以正常登录，但是efb登录报错

```
2022-01-03 22:42:27,704 [Level 99]: plugins.blueset.wechat.WeChatChannel (__init__.console_qr_code; __init__.py:192)

    Confirm on your phone.

2022-01-03 22:42:35,045 [Level 99]: plugins.blueset.wechat.WeChatChannel (__init__.console_qr_code; __init__.py:195)

    Successfully logged in.

2022-01-03 22:42:36,268 [Level 99]: ehforwarderbot.__main__ (__main__.init; __main__.py:137)

     Slave channel WeChat Slave (blueset.wechat) # Default profile is initialized. 

2022-01-03 22:42:36,269 [Level 99]: ehforwarderbot.__main__ (__main__.init; __main__.py:142)

     Initializing master blueset.telegram... 

Exception in thread itchat polling thread (maintain_loop):

Traceback (most recent call last):

  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner

    self.run()

  File "/usr/lib/python3.8/threading.py", line 870, in run

    self._target(*self._args, **self._kwargs)

  File "/usr/lib/python3.8/site-packages/efb_wechat_slave/vendor/itchat/components/login.py", line 295, in maintain_loop

    exitCallback()

  File "/usr/lib/python3.8/site-packages/efb_wechat_slave/__init__.py", line 261, in exit_callback

    raise Exception(

Exception: Web WeChat logged your account out before master channel is ready.

2022-01-03 22:42:37,416 [Level 99]: ehforwarderbot.__main__ (__main__.init; __main__.py:149)

     Master channel Telegram Master (blueset.telegram) # Default profile is initialized. 

2022-01-03 22:42:37,417 [Level 99]: ehforwarderbot.__main__ (__main__.init; __main__.py:155)

     All channels initialized. 

2022-01-03 22:42:37,417 [Level 99]: ehforwarderbot.__main__ (__main__.init; __main__.py:169)

     All middlewares are initialized.
```

**Comment by gaxdel** [comment]
> 我的是网页文件助手复活的，31号下线了，在本地网页版可以正常登录，但是efb登录报错
> 
> ```
> 2022-01-03 22:42:27,704 [Level 99]: plugins.blueset.wechat.WeChatChannel (__init__.console_qr_code; __init__.py:192)
> 
>     Confirm on your phone.
> 
> 2022-01-03 22:42:35,045 [Level 99]: plugins.blueset.wechat.WeChatChannel (__init__.console_qr_code; __init__.py:195)
> 
>     Successfully logged in.
> 
> 2022-01-03 22:42:36,268 [Level 99]: ehforwarderbot.__main__ (__main__.init; __main__.py:137)
> 
>      Slave channel WeChat Slave (blueset.wechat) # Default profile is initialized. 
> 
> 2022-01-03 22:42:36,269 [Level 99]: ehforwarderbot.__main__ (__main__.init; __main__.py:142)
> 
>      Initializing master blueset.telegram... 
> 
> Exception in thread itchat polling thread (maintain_loop):
> 
> Traceback (most recent call last):
> 
>   File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
> 
>     self.run()
> 
>   File "/usr/lib/python3.8/threading.py", line 870, in run
> 
>     self._target(*self._args, **self._kwargs)
> 
>   File "/usr/lib/python3.8/site-packages/efb_wechat_slave/vendor/itchat/components/login.py", line 295, in maintain_loop
> 
>     exitCallback()
> 
>   File "/usr/lib/python3.8/site-packages/efb_wechat_slave/__init__.py", line 261, in exit_callback
> 
>     raise Exception(
> 
> Exception: Web WeChat logged your account out before master channel is ready.
> 
> 2022-01-03 22:42:37,416 [Level 99]: ehforwarderbot.__main__ (__main__.init; __main__.py:149)
> 
>      Master channel Telegram Master (blueset.telegram) # Default profile is initialized. 
> 
> 2022-01-03 22:42:37,417 [Level 99]: ehforwarderbot.__main__ (__main__.init; __main__.py:155)
> 
>      All channels initialized. 
> 
> 2022-01-03 22:42:37,417 [Level 99]: ehforwarderbot.__main__ (__main__.init; __main__.py:169)
> 
>      All middlewares are initialized.
> ```

按照 #126 改下/usr/lib/python3.8/site-packages/efb_wechat_slave/vendor/itchat/components/login.py 文件，我改了之后能登录了。

**Comment by fpGHwd** [comment]
> 我的是网页文件助手复活的，31号下线了，在本地网页版可以正常登录，但是efb登录报错
> 
> 更新 更改了login.py或者降级2.0.4 都试了 仍然不行 然后删除了Session 清除后重新登录就可以了 不确定那个起作用了 还不能登录的可以试试
> 
> ```
> 2022-01-03 22:42:27,704 [Level 99]: plugins.blueset.wechat.WeChatChannel (__init__.console_qr_code; __init__.py:192)
> 
>     Confirm on your phone.
> 
> 2022-01-03 22:42:35,045 [Level 99]: plugins.blueset.wechat.WeChatChannel (__init__.console_qr_code; __init__.py:195)
> 
>     Successfully logged in.
> 
> 2022-01-03 22:42:36,268 [Level 99]: ehforwarderbot.__main__ (__main__.init; __main__.py:137)
> 
>      Slave channel WeChat Slave (blueset.wechat) # Default profile is initialized. 
> 
> 2022-01-03 22:42:36,269 [Level 99]: ehforwarderbot.__main__ (__main__.init; __main__.py:142)
> 
>      Initializing master blueset.telegram... 
> 
> Exception in thread itchat polling thread (maintain_loop):
> 
> Traceback (most recent call last):
> 
>   File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
> 
>     self.run()
> 
>   File "/usr/lib/python3.8/threading.py", line 870, in run
> 
>     self._target(*self._args, **self._kwargs)
> 
>   File "/usr/lib/python3.8/site-packages/efb_wechat_slave/vendor/itchat/components/login.py", line 295, in maintain_loop
> 
>     exitCallback()
> 
>   File "/usr/lib/python3.8/site-packages/efb_wechat_slave/__init__.py", line 261, in exit_callback
> 
>     raise Exception(
> 
> Exception: Web WeChat logged your account out before master channel is ready.
> 
> 2022-01-03 22:42:37,416 [Level 99]: ehforwarderbot.__main__ (__main__.init; __main__.py:149)
> 
>      Master channel Telegram Master (blueset.telegram) # Default profile is initialized. 
> 
> 2022-01-03 22:42:37,417 [Level 99]: ehforwarderbot.__main__ (__main__.init; __main__.py:155)
> 
>      All channels initialized. 
> 
> 2022-01-03 22:42:37,417 [Level 99]: ehforwarderbot.__main__ (__main__.init; __main__.py:169)
> 
>      All middlewares are initialized.
> ```

遇到相同的现象， ehforwarderbot 为最新版 2.1.11 ，多次清除 session 文件登录依然此异常。最后退回版本 2.0.4 重新启动服务正常。非常感谢你提供的细节！

**Comment by hookjk100** [comment]
efb-wechat 难民营，希望能找到解决办法，互通有无：
https://t.me/+G4v4Jdqrwp1mODc5

**Comment by zbuhui** [comment]
> @artxia 感谢提醒，已将补丁应用到 EWS 的 itchat 里面。（ [8312b76](https://github.com/ehForwarderBot/efb-wechat-slave/commit/8312b767f47328f8da3a83817c51e59190815322) ） 已推送到 GitHub，待发布到 PyPI。

@blueset 2024.1.23 用了这位大佬的[插件](https://github.com/lqzhgood/wechat-need-web)可以登录,其他的貌似都失效了.(2023 年 1 月：Chrome 浏览器将不再运行 Manifest V2 扩展程序) 希望EFB能跟进,谢谢

**Comment by magisk317** [comment]
#152 
不知道算不算喜报，先关联一下，希望能有大手子搞下
