### ISSUE TITLE
EFB Telegram 主端遇到错误 'Message' object has no attribute 'message'

### ISSUE THREAD

**Issue by bao3** [blueset/efb-wechat-slave#70]
### 版本信息
```
# ehforwarderbot -V
EH Forwarder Bot
Version: 2.0.0b19
Python version:
3.6.9 (default, Aug  8 2019, 01:20:04)
[GCC 4.2.1 Compatible FreeBSD Clang 6.0.1 (tags/RELEASE_601/final 335540)]
Running on profile "default".

Master channel:
    Telegram Master (blueset.telegram) 2.0.0b19 # Default instance

Slave channel:
    WeChat Slave (blueset.wechat) 2.0.0a29.dev3 # Default instance

Middlewares:
    No middleware is enabled.
```
### 问题描述

在 Telegram 上输入任何指令，都会弹出红字错误，提示如下：

```
EFB Telegram 主端遇到错误 'Message' object has no attribute 'message'。
来自状态：{'update_id': 191, 'message': {'message_id':  5, 'date':  88, 'chat': {'id':  236, 'type': 'private', 'username': ' d', 'first_name': 'Bra', 'last_name': 'Wa'}, 'text': '/info', 'entities': [{'type': 'bot_command', 'offset': 0, 'length': 5}], 'caption_entities': [], 'photo': [], 'new_chat_members': [], 'new_chat_photo': [], 'delete_chat_photo': False, 'group_chat_created': False, 'supergroup_chat_created': False, 'channel_chat_created': False, 'from': {'id':  8236, 'first_name': 'Bra', 'is_bot': False, 'last_name': 'Wa', 'username': 'd', 'language_code': 'zh-hans'}}, '_effective_user': {'id': 8236, 'first_name': 'Bra', 'is_bot': False, 'last_name': 'Wa', 'username': 'd', 'language_code': 'zh-hans'}}。
```

### 重现步骤
使用 pip 升级了所有的包，结果出现了这个错误

```
import subprocess as sbp
import pip
pkgs = eval(str(sbp.run("pip3 list -o --format=json", shell=True,
                         stdout=sbp.PIPE).stdout, encoding='utf-8'))
for pkg in pkgs:
    sbp.run("pip3 install --upgrade " + pkg['name'], shell=True)
```

### Verbose 日志
<details>
<summary>Verbose 日志</summary>

```
2019-09-19 01:35:06,834 [DEBUG]: efb_telegram_master.locale_handler (locale_handler.check_update; locale_handler.py:36)
    [582541191] Update has language zh-hans.
2019-09-19 01:35:06,834 [INFO]: efb_telegram_master.locale_handler (locale_handler.check_update; locale_handler.py:46)
    Updating locale to zh
--- Logging error ---
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/efb_telegram_master/__init__.py", line 339, in error
    raise error
  File "/usr/local/lib/python3.6/site-packages/telegram/ext/dispatcher.py", line 368, in process_update
    check = handler.check_update(update)
  File "/usr/local/lib/python3.6/site-packages/efb_telegram_master/global_command_handler.py", line 34, in check_update
    res = self.filters(message)
  File "/usr/local/lib/python3.6/site-packages/telegram/ext/filters.py", line 87, in __call__
    return self.filter(update)
  File "/usr/local/lib/python3.6/site-packages/telegram/ext/filters.py", line 935, in filter
    return update.message is not None or update.edited_message is not None
AttributeError: 'Message' object has no attribute 'message'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/logging/__init__.py", line 994, in emit
    msg = self.format(record)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 840, in format
    return fmt.format(record)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 577, in format
    record.message = record.getMessage()
  File "/usr/local/lib/python3.6/logging/__init__.py", line 338, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/local/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/site-packages/telegram/ext/updater.py", line 169, in _thread_wrapper
    target(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/telegram/ext/dispatcher.py", line 277, in start
    self.process_update(update)
  File "/usr/local/lib/python3.6/site-packages/telegram/ext/dispatcher.py", line 385, in process_update
    self.dispatch_error(update, e)
  File "/usr/local/lib/python3.6/site-packages/telegram/ext/dispatcher.py", line 509, in dispatch_error
    callback(self.bot, update, error)
  File "/usr/local/lib/python3.6/site-packages/efb_telegram_master/__init__.py", line 405, in error
    'Update %s caused error %s. Exception', update, error, e)
Message: 'Unhandled telegram bot error!\nUpdate %s caused error %s. Exception'
Arguments: (<telegram.update.Update object at 0x8043322e8>, AttributeError("'Message' object has no attribute 'message'",), AttributeError("'Message' object has no attribute 'message'",))
```
 
</details>

**Comment by blueset** [comment]
现在的 ETM 最新版是 beta 26，请确保您使用的 `pip` 连接到了 PyPI 官方仓库。部分镜像仓库可能在更新上有所延迟。
