### ISSUE TITLE
最新版报错 

### ISSUE THREAD

**Issue by shzxm** [blueset/efb-wechat-slave#73]
ubuntu 18.04 lst

```
2019-10-14 09:26:44,783 [ERROR]: telegram.vendor.ptb_urllib3.urllib3.connection (connection._match_hostname; connection.py:356)
    Certificate did not match expected hostname: api.telegram.org. Certificate: {'subject': ((('commonName', 'redirweb2.reg.free.org'),),), 'issuer': ((('countryName', 'US'),), (('organizationName', "Let's Encrypt"),), (('commonName', "Let's Encrypt Authority X3"),)), 'version': 3, 'serialNumber': '030D170B3D5DB746108F5BB25CBCEF7C918D', 'notBefore': 'Aug 24 01:15:08 2019 GMT', 'notAfter': 'Nov 22 01:15:08 2019 GMT', 'subjectAltName': (('DNS', 'redirweb2.reg.free.org'),), 'OCSP': ('http://ocsp.int-x3.letsencrypt.org',), 'caIssuers': ('http://cert.int-x3.letsencrypt.org/',)}
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 617, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.6/dist-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 360, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.6/dist-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 857, in _validate_conn
    super(HTTPSConnectionPool, self)._validate_conn(conn)
  File "/usr/local/lib/python3.6/dist-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 289, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.6/dist-packages/telegram/vendor/ptb_urllib3/urllib3/connection.py", line 342, in connect
    _match_hostname(cert, self.assert_hostname or hostname)
  File "/usr/local/lib/python3.6/dist-packages/telegram/vendor/ptb_urllib3/urllib3/connection.py", line 352, in _match_hostname
    match_hostname(cert, asserted_hostname)
  File "/usr/lib/python3.6/ssl.py", line 331, in match_hostname
    % (hostname, dnsnames[0]))
ssl.CertificateError: hostname 'api.telegram.org' doesn't match 'redirweb2.reg.free.org'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py", line 218, in _request_wrapper
    resp = self._con_pool.request(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/telegram/vendor/ptb_urllib3/urllib3/request.py", line 66, in request
    **urlopen_kw)
  File "/usr/local/lib/python3.6/dist-packages/telegram/vendor/ptb_urllib3/urllib3/request.py", line 87, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "/usr/local/lib/python3.6/dist-packages/telegram/vendor/ptb_urllib3/urllib3/poolmanager.py", line 244, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/local/lib/python3.6/dist-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 647, in urlopen
    raise SSLError(e)
telegram.vendor.ptb_urllib3.urllib3.exceptions.SSLError: hostname 'api.telegram.org' doesn't match 'redirweb2.reg.free.org'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/ehforwarderbot", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/ehforwarderbot/__main__.py", line 269, in main
    init(conf)
  File "/usr/local/lib/python3.6/dist-packages/ehforwarderbot/__main__.py", line 103, in init
    coordinator.add_channel(module(instance_id=instance_id))
  File "/usr/local/lib/python3.6/dist-packages/efb_telegram_master/__init__.py", line 129, in __init__
    self.bot_manager: TelegramBotManager = TelegramBotManager(self)
  File "/usr/local/lib/python3.6/dist-packages/efb_telegram_master/bot_manager.py", line 86, in __init__
    self.me: telegram.User = self.updater.bot.get_me()
  File "/usr/local/lib/python3.6/dist-packages/telegram/bot.py", line 66, in decorator
    result = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/telegram/bot.py", line 199, in get_me
    result = self._request.get(url, timeout=timeout)
  File "/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py", line 270, in get
    result = self._request_wrapper('GET', url, **urlopen_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py", line 224, in _request_wrapper
    raise NetworkError('urllib3 HTTPError {0}'.format(error))
telegram.error.NetworkError: urllib3 HTTPError hostname 'api.telegram.org' doesn't match 'redirweb2.reg.free.org'
2019-10-14 09:27:01,092 [ERROR]: efb_wechat_slave.vendor.wxpy.api.bot (bot.process; bot.py:459)
    an error occurred in <bound method SlaveMessageManager.Decorators.wechat_msg_meta.<locals>.thread_wrapper of <efb_wechat_slave.slave_message.SlaveMessageManager object at 0x7f1283ab9a20>>.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/efb_wechat_slave/vendor/wxpy/api/bot.py", line 455, in process
    ret = config.func(msg)
  File "/usr/local/lib/python3.6/dist-packages/efb_wechat_slave/slave_message.py", line 79, in thread_wrapper
    threading.Thread(target=wrap_func, args=args, kwargs=kwargs).run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/dist-packages/efb_wechat_slave/slave_message.py", line 71, in wrap_func
    efb_msg.deliver_to = coordinator.master
AttributeError: module 'ehforwarderbot.coordinator' has no attribute 'master'
2019-10-14 09:27:50,982 [ERROR]: efb_wechat_slave.vendor.wxpy.api.bot (bot.process; bot.py:459)
    an error occurred in <bound method SlaveMessageManager.Decorators.wechat_msg_meta.<locals>.thread_wrapper of <efb_wechat_slave.slave_message.SlaveMessageManager object at 0x7f1283ab9a20>>.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/efb_wechat_slave/vendor/wxpy/api/bot.py", line 455, in process
    ret = config.func(msg)
  File "/usr/local/lib/python3.6/dist-packages/efb_wechat_slave/slave_message.py", line 79, in thread_wrapper
    threading.Thread(target=wrap_func, args=args, kwargs=kwargs).run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/dist-packages/efb_wechat_slave/slave_message.py", line 71, in wrap_func
    efb_msg.deliver_to = coordinator.master
AttributeError: module 'ehforwarderbot.coordinator' has no attribute 'master'
2019-10-14 09:27:52,242 [ERROR]: efb_wechat_slave.vendor.wxpy.api.bot (bot.process; bot.py:459)
    an error occurred in <bound method SlaveMessageManager.Decorators.wechat_msg_meta.<locals>.thread_wrapper of <efb_wechat_slave.slave_message.SlaveMessageManager object at 0x7f1283ab9a20>>.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/efb_wechat_slave/vendor/wxpy/api/bot.py", line 455, in process
    ret = config.func(msg)
  File "/usr/local/lib/python3.6/dist-packages/efb_wechat_slave/slave_message.py", line 79, in thread_wrapper
    threading.Thread(target=wrap_func, args=args, kwargs=kwargs).run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/dist-packages/efb_wechat_slave/slave_message.py", line 71, in wrap_func
    efb_msg.deliver_to = coordinator.master
AttributeError: module 'ehforwarderbot.coordinator' has no attribute 'master'
^CException ignored in: <module 'threading' from '/usr/lib/python3.6/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 1294, in _shutdown
    t.join()
  File "/usr/lib/python3.6/threading.py", line 1056, in join
    self._wait_for_tstate_lock()
  File "/usr/lib/python3.6/threading.py", line 1072, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
```

**Comment by blueset** [comment]
```
ssl.CertificateError: hostname 'api.telegram.org' doesn't match 'redirweb2.reg.free.org'
```

请检查您的运行环境到 Telegram Bot API 的连接是否被阻断，谢谢。
