### ISSUE TITLE
update_info报错

### ISSUE THREAD

**Issue by yswtrue** [blueset/efb-wechat-slave#78]
### 版本信息
2.0.0b20

### 问题描述
执行update_info报错

### 重现步骤
在聊天框输入update_info

### Verbose 日志

```
efb_master | 2019-10-21 17:05:50,887 [ERROR]: efb_telegram_master.chat_binding (chat_binding.update_group_info; chat_binding.py:798)
efb_master |     Error occurred while update chat details.
efb_master | Traceback (most recent call last):
efb_master |   File "/usr/local/lib/python3.7/site-packages/efb_telegram_master/chat_binding.py", line 771, in update_group_info
efb_master |     self.bot.set_chat_title(tg_chat, chat.chat_title)
efb_master |   File "/usr/local/lib/python3.7/site-packages/efb_telegram_master/bot_manager.py", line 484, in set_chat_title
efb_master |     return self.updater.bot.set_chat_title(*args, **kwargs)
efb_master |   File "/usr/local/lib/python3.7/site-packages/telegram/bot.py", line 66, in decorator
efb_master |     result = func(self, *args, **kwargs)
efb_master |   File "/usr/local/lib/python3.7/site-packages/telegram/bot.py", line 2974, in set_chat_title
efb_master |     result = self._request.post(url, data, timeout=timeout)
efb_master |   File "/usr/local/lib/python3.7/site-packages/telegram/utils/request.py", line 327, in post
efb_master |     **urlopen_kwargs)
efb_master |   File "/usr/local/lib/python3.7/site-packages/telegram/utils/request.py", line 238, in _request_wrapper
efb_master |     raise BadRequest(message)
efb_master | telegram.error.BadRequest: Not enough rights to change chat title
```

**Comment by yswtrue** [comment]
看了其他issue解决了

**Comment by blueset** [comment]
附注：
> _Not enough rights to change chat title_
> 权限不足，无法更改会话标题。
