### ISSUE TITLE
/chat报错

### ISSUE THREAD

**Issue by yswtrue** [blueset/efb-wechat-slave#79]
### 版本信息
2.0.0b20

### 问题描述
群组聊天框输入/chat，出错

### 重现步骤
群组聊天框输入/chat，出错

### Verbose 日志
```
efb_master | 2019-10-21 17:07:52,124 [ERROR]: efb_telegram_master (__init__.error; __init__.py:507)
efb_master |     Unhandled telegram bot error!
efb_master | Update {'update_id': 610946360, 'message': {'message_id': 162, 'date': 1571677670, 'chat': {'id': -338824557, 'type': 'group', 'title': 'Jeam', 'all_members_are_administrators': True}, 'text': '/chat@RoyEfbBot', 'entities': [{'type': 'bot_command', 'offset': 0, 'length': 15}], 'caption_entities': [], 'photo': [], 'new_chat_members': [], 'new_chat_photo': [], 'delete_chat_photo': False, 'group_chat_created': False, 'supergroup_chat_created': False, 'channel_chat_created': False, 'from': {'id': 908152108, 'first_name': 'Roy', 'is_bot': False, 'language_code': 'en'}}, '_effective_user': {'id': 908152108, 'first_name': 'Roy', 'is_bot': False, 'language_code': 'en'}, '_effective_chat': {'id': -338824557, 'type': 'group', 'title': 'Jeam', 'all_members_are_administrators': True}, '_effective_message': {'message_id': 162, 'date': 1571677670, 'chat': {'id': -338824557, 'type': 'group', 'title': 'Jeam', 'all_members_are_administrators': True}, 'text': '/chat@RoyEfbBot', 'entities': [{'type': 'bot_command', 'offset': 0, 'length': 15}], 'caption_entities': [], 'photo': [], 'new_chat_members': [], 'new_chat_photo': [], 'delete_chat_photo': False, 'group_chat_created': False, 'supergroup_chat_created': False, 'channel_chat_created': False, 'from': {'id': 908152108, 'first_name': 'Roy', 'is_bot': False, 'language_code': 'en'}}} caused error . Exception
efb_master | Traceback (most recent call last):
efb_master |   File "/usr/local/lib/python3.7/site-packages/efb_telegram_master/__init__.py", line 437, in error
efb_master |     raise error
efb_master |   File "/usr/local/lib/python3.7/site-packages/telegram/ext/dispatcher.py", line 372, in process_update
efb_master |     handler.handle_update(update, self, check, context)
efb_master |   File "/usr/local/lib/python3.7/site-packages/telegram/ext/handler.py", line 117, in handle_update
efb_master |     return self.callback(update, context)
efb_master |   File "/usr/local/lib/python3.7/site-packages/efb_telegram_master/chat_binding.py", line 558, in start_chat_list
efb_master |     return self.chat_head_req_generate(target, pattern=" ".join(args), chats=chats)
efb_master |   File "/usr/local/lib/python3.7/site-packages/efb_telegram_master/chat_binding.py", line 585, in chat_head_req_generate
efb_master |     channel.get_chat(slave_chat_id))
efb_master |   File "/usr/local/lib/python3.7/site-packages/efb_telegram_master/chat.py", line 26, in __init__
efb_master |     assert db
efb_master | AssertionError

```

**Comment by blueset** [comment]
已于 [ETM#74](https://github.com/blueset/efb-telegram-master/pull/74) 中修复，将于下一版本发布。

Duplicate of blueset/efb-telegram-master#74.
