### ISSUE TITLE
重新登录报错

### ISSUE THREAD

**Issue by yswtrue** [blueset/efb-wechat-slave#80]
### 版本信息
2.0.0b20

### 问题描述
重新登录报错

### 重现步骤
过了一晚，回来在看提示我已经下线了，需要重新登录，我点击重新登录就报错了

### Verbose 日志
<details>
<summary>Verbose 日志</summary>

```
efb_master | 2019-10-22 01:56:35,752 [ERROR]: efb_telegram_master (__init__.error; __init__.py:507)
efb_master |     Unhandled telegram bot error!
efb_master | Update {'update_id': 610946437, 'callback_query': {'id': '3900483605138115839', 'chat_instance': '-3555724164525691228', 'message': {'message_id': 250, 'date': 1571698591, 'chat': {'id': 908152108, 'type': 'private', 'first_name': 'Roy'}, 'text': '💬💻 EWS User Auth:\nWeChat server has logged you out. Please log in again when you are ready.', 'entities': [], 'caption_entities': [], 'photo': [], 'new_chat_members': [], 'new_chat_photo': [], 'delete_chat_photo': False, 'group_chat_created': False, 'supergroup_chat_created': False, 'channel_chat_created': False, 'reply_markup': {'inline_keyboard': [[{'text': 'Log in again', 'callback_data': '0'}]]}, 'from': {'id': 943916051, 'first_name': 'Efb', 'is_bot': True, 'username': 'RoyEfbBot'}}, 'data': '0', 'from': {'id': 908152108, 'first_name': 'Roy', 'is_bot': False, 'language_code': 'en'}}, '_effective_user': {'id': 908152108, 'first_name': 'Roy', 'is_bot': False, 'language_code': 'en'}, '_effective_chat': {'id': 908152108, 'type': 'private', 'first_name': 'Roy'}, '_effective_message': {'message_id': 250, 'date': 1571698591, 'chat': {'id': 908152108, 'type': 'private', 'first_name': 'Roy'}, 'text': '💬💻 EWS User Auth:\nWeChat server has logged you out. Please log in again when you are ready.', 'entities': [], 'caption_entities': [], 'photo': [], 'new_chat_members': [], 'new_chat_photo': [], 'delete_chat_photo': False, 'group_chat_created': False, 'supergroup_chat_created': False, 'channel_chat_created': False, 'reply_markup': {'inline_keyboard': [[{'text': 'Log in again', 'callback_data': '0'}]]}, 'from': {'id': 943916051, 'first_name': 'Efb', 'is_bot': True, 'username': 'RoyEfbBot'}}} caused error edit_message_reply_markup() missing 1 required positional argument: 'reply_markup'. Exception
efb_master | Traceback (most recent call last):
efb_master |   File "/usr/local/lib/python3.7/site-packages/efb_telegram_master/__init__.py", line 437, in error
efb_master |     raise error
efb_master |   File "/usr/local/lib/python3.7/site-packages/telegram/ext/dispatcher.py", line 372, in process_update
efb_master |     handler.handle_update(update, self, check, context)
efb_master |   File "/usr/local/lib/python3.7/site-packages/telegram/ext/conversationhandler.py", line 343, in handle_update
efb_master |     new_state = handler.handle_update(update, dispatcher, check_result, context)
efb_master |   File "/usr/local/lib/python3.7/site-packages/telegram/ext/handler.py", line 117, in handle_update
efb_master |     return self.callback(update, context)
efb_master |   File "/usr/local/lib/python3.7/site-packages/efb_telegram_master/commands.py", line 106, in command_exec
efb_master |     update.callback_query.edit_message_reply_markup()
efb_master | TypeError: edit_message_reply_markup() missing 1 required positional argument: 'reply_markup'

```
 
</details>

**Comment by blueset** [comment]
> Repository: [EFB Telegram Master](https://etm.1a23.studio)

已修复，将在下一版本发布。

**Comment by blueset** [comment]
已发布。

**Comment by yswtrue** [comment]
非常感谢
