### ISSUE TITLE
在windows下运行，提示权限拒绝。且不能收发表情、图片

### ISSUE THREAD

**Issue by kettly1260** [blueset/efb-wechat-slave#92]
### 版本信息

您正在使用 EFB Telegram 主端 2.0.0b36，运行于配置档案「a」、默认实例、EFB 版本 2.0.0b23。
已激活 1 个从端：
- 💬 WeChat Slave (blueset.wechat, 2.0.0a35)

### 问题描述

在windows下以管理员运行项目，会提示没有权限在临时文件夹写入文件。另外，无法接受和发送表情和图片。在接收图片时TG没有任何提示。

### 重现步骤

接受、发送图片和表情可复现

### Verbose 日志
<details>
<summary>Verbose 日志</summary>

```
接收图片：
2019-12-30 09:05:53,056 [ERROR]: efb_wechat_slave.vendor.wxpy.api.bot (bot.process; bot.py:465)
    an error occurred in <bound method SlaveMessageManager.Decorators.wechat_msg_meta.<locals>.thread_wrapper of <efb_wechat_slave.slave_message.SlaveMessageManager object at 0x000002899CCD6FD0>>.
Traceback (most recent call last):
  File "c:\program files\python\lib\site-packages\efb_wechat_slave\vendor\wxpy\api\bot.py", line 461, in process
    ret = config.func(msg)
  File "c:\program files\python\lib\site-packages\efb_wechat_slave\slave_message.py", line 91, in thread_wrapper
    threading.Thread(target=wrap_func, args=args, kwargs=kwargs, name=f"EWS slave message thread running {func}").run()
  File "c:\program files\python\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "c:\program files\python\lib\site-packages\efb_wechat_slave\slave_message.py", line 59, in wrap_func
    efb_msg: Optional[EFBMsg] = func(self, msg, *args, **kwargs)
  File "c:\program files\python\lib\site-packages\efb_wechat_slave\slave_message.py", line 331, in wechat_picture_msg
    efb_msg.path, efb_msg.mime, efb_msg.file = self.save_file(msg)
  File "c:\program files\python\lib\site-packages\efb_wechat_slave\slave_message.py", line 464, in save_file
    msg.get_file(file.name)
  File "c:\program files\python\lib\site-packages\efb_wechat_slave\vendor\wxpy\api\messages\message.py", line 137, in get_file
    return _text(save_path)
  File "c:\program files\python\lib\site-packages\efb_wechat_slave\vendor\itchat\components\messages.py", line 40, in download_fn
    with open(downloadDir, 'wb') as f:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\YING-O~1\\AppData\\Local\\Temp\\tmp0t674fcl'

发送图片：
Traceback (most recent call last):
  File "c:\program files\python\lib\site-packages\moviepy\video\io\ffmpeg_reader.py", line 289, in ffmpeg_parse_infos
    line = [l for l in lines if keyword in l][index]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\program files\python\lib\site-packages\efb_telegram_master\master_message.py", line 96, in message_worker
    self.msg(update, context)
  File "c:\program files\python\lib\site-packages\efb_telegram_master\master_message.py", line 156, in msg
    return self.process_telegram_message(update, context)
  File "c:\program files\python\lib\site-packages\efb_telegram_master\master_message.py", line 433, in process_telegram_message
    if m.file:
  File "c:\program files\python\lib\site-packages\efb_telegram_master\message.py", line 124, in get_file
    self._load_file()
  File "c:\program files\python\lib\site-packages\efb_telegram_master\message.py", line 77, in _load_file
    v = VideoFileClip(file.name)
  File "c:\program files\python\lib\site-packages\moviepy\video\io\VideoFileClip.py", line 91, in __init__
    fps_source=fps_source)
  File "c:\program files\python\lib\site-packages\moviepy\video\io\ffmpeg_reader.py", line 33, in __init__
    fps_source)
  File "c:\program files\python\lib\site-packages\moviepy\video\io\ffmpeg_reader.py", line 295, in ffmpeg_parse_infos
    filename, infos))
OSError: MoviePy error: failed to read the duration of file C:\Users\YING-O~1\AppData\Local\Temp\tmporl_42rf.mp4.
Here are the file infos returned by ffmpeg:

ffmpeg version 4.1 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 8.2.1 (GCC) 20181017
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
  libpostproc    55.  3.100 / 55.  3.100
C:\Users\YING-O~1\AppData\Local\Temp\tmporl_42rf.mp4: Permission denied

```
 
</details>

**Comment by blueset** [comment]
感谢汇报。该问题是由于 Windows 的系统架构导致的。根据 [Python 开发文档][0]，其创建的临时文件在 Windows NT 架构的系统中不能被二次打开。而 EFB Telegram 主端（ETM）依赖该功能进行文件类型识别以及媒体转码（通过 `libmagic` 以及 `ffmpeg`）。

目前我们还没有找到解决办法来让外部软件包或进程来调用 Python 的文件句柄（file handle）。有关此问题我们在 ETM 方面开了一个[新的 issue][1] 来追踪这个问题并寻求帮助。

[0]: https://docs.python.org/3.8/library/tempfile.html#tempfile.NamedTemporaryFile
[1]: https://github.com/blueset/efb-telegram-master/issues/90

**Comment by blueset** [comment]
已尝试于 ETM 2.0.0b45 进行修复。如仍有疑问，请移步 https://github.com/blueset/efb-telegram-master/issues/90 。
