### ISSUE TITLE
使用efb-wizard配置experimental features时出错

### ISSUE THREAD

**Issue by chenyc1995** [blueset/efb-wechat-slave#99]
#81 
# 版本信息
EH Forwarder Bot
Version: 2.0.0
Python version:
3.6.10 (default, Dec 19 2019, 23:04:32) 
[GCC 5.4.0 20160609]
Running on profile "default".

Master channel:
    Telegram Master (blueset.telegram) 2.0.2 # Default instance

Slave channel:
    WeChat Slave (blueset.wechat) 2.0.0 # Default instance

### 问题描述
使用efb-wizard配置experimental features时出错

### 重现步骤
使用efb-wizard配置efb-wechat-slave时是否配置experimental features选“y”。之后配置到“qr_reload”项结束后即出现错误。

### Verbose 日志

<details>

```
qr_reload [master_qr_code]: master_qr_code

on_log_out
Behavior when WeChat server logged your account out.

Options:
-  "idle": Only notify the user.
-  "reauth": Notify the user and start log in immediately.
-  "command": Notify the user, and wait for user to start log in
manually.
on_log_out?
Traceback (most recent call last):
  File "/usr/local/bin/efb-wizard", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/ehforwarderbot/wizard.py", line 698, in main
    data.modules[mid].wizard(data.profile, iid)
  File "/usr/local/lib/python3.6/dist-packages/efb_wechat_slave/wizard.py", line 219, in wizard
    setup_experimental_flags(data)
  File "/usr/local/lib/python3.6/dist-packages/efb_wechat_slave/wizard.py", line 187, in setup_experimental_flags
    .launch(default=default)
  File "/usr/local/lib/python3.6/dist-packages/bullet/client.py", line 214, in launch
    raise TypeError("'default' should be an integer value!")
TypeError: 'default' should be an integer value!
```
</details>

**Comment by blueset** [comment]
感谢汇报，将于 EWS 2.0.1 版本修复。
